- README.md
We can add more details later.
> simple README

- gate-web/gate-web.gradle
> only reference /opt in the startScripts

- build.gradle
- gate-web/config/gate.yml
- gate-web/config/hystrix.properties
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/Main.groovy
- gradle/wrapper/gradle-wrapper.properties
Requires merge and release of:
https://github.com/spinnaker/kork/pull/26
https://github.com/spinnaker/spinnaker-dependencies/pull/7
> Update kork to pick up archaius configuration for hystrix.

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ClusterController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ClusterService.groovy
provide Spinnaker API callers access to target server group lookup endpoint
> exposes TargetServerGroup lookup endpoint from clouddriver

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ProjectController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ProjectService.groovy
@ajordens or @cfieber review eh
> add project clusters endpoint

- gate-web/config/gate.yml
> make trusty the default baseos option when reading from config

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CronService.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/CronServiceSpec.groovy
Needed to include English description on validated cron expressions
> include description on successful cron validation

- build.gradle
- gate-web/gate-web.gradle
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
This reverts commit 7b889cfc91ffae7b3681ae9a29149eb0e3dc1fdb.
> Revert the kork update and do the OkHttp setting just in gate

- build.gradle
- gate-web/gate-web.gradle
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/TaskService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaService.groovy
> fixes for SPIN-1333 and SPIN-1383

- gate-web/etc/init/gate.conf
this change works together with PR by @ewiseblatt
https://github.com/spinnaker/spinnaker/pull/784
> auto start gate service if gate is installed standalone, issue #762

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CloudMetricController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CloudMetricService.groovy
Transparent passthrough endpoints with some Hystrix for good measure
@ajordens or other @spinnaker/netflix-reviewers PTAL
> add cloudMetrics endpoints

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuth2SecurityController.groovy
Added @ConditionalOnExpression for OAuth2 Controller so that this is backwards compatible.
> Added @ConditionalOnExpression for OAuth2 Controller.

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuth2SecurityController.groovy
Removed unused autowired field in OAuth controller, this is handled by OAuth2Configuration.
> Removed unused autowired field in OAuth controller.

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/JobController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/JobService.groovy
> core: Handle job requests

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/SpinnakerAuthConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/anonymous/AnonymousConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/client/OAuth2SsoConfig.groovy
> Makes anonymous auth work again, but using the standard anonymous() configurer

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/AuthController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/AuthConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/SpinnakerUser.groovy
> Enables Deck workflow by introducting simple redirect endpoint.

- gate-web/gate-web.gradle
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/client/OAuth2SsoConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/SpinnakerUserRolesProvider.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/google/GoogleDirectoryUserRolesProvider.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/google/GoogleDirectoryUserRolesProviderConfig.groovy
Added UserRolesProvider interface and Google Directory implementation. Also added default `UserRolesProvider` if none configured. @ttomsu PTAL.
> Added UserRolesProvider interface and Google Directory impl.

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/config/Headers.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/AuthController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/SpinnakerUser.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/SpinnakerUserDetails.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/anonymous/AnonymousConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/client/OAuth2SsoConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509Config.groovy
> Make all configs use SpinnakerUserDetails

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/InsightConfiguration.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/JobController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/JobService.groovy
> core: Job Details Endpoint

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/AuthConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuth2SsoConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/google/GoogleDirectoryUserRolesProvider.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsService.groovy
Populates UserRoles in x509 auth flow. @ttomsu PTAL.
> Populates UserRoles in x509 auth flow.

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
Updates for https://github.com/spring-projects/spring-security-saml-dsl/pull/21/files
cc @ttomsu
> Updates for spring-projects/spring-security-saml-dsl#21

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
> SamlSsoConfigurers optional

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuth2SsoConfig.groovy
Many hours of frustrating configuration has brought you this 3 line PR, @rguthriemsft @scotmoor.
> Extracts MSFT Azure AD-specific User values.

- gate-web/gate-web.gradle
Big thanks to @rwinch for pushing the milestone build through.
@cfieber, @jtk54, @riltsken FYI
> SAML DSL to M1 snapshot, enable spring.profiles.active passthrough

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
Found by @ajordens
@riltsken FYI
> Nits on extracting SAML attributes

- gate-web/config/gate.yml
Fixed property indentation causing build to fail. @ttomsu @scotmoor @rguthriemsft FYI
> Fixed property indentation causing build to fail.

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/AuthController.groovy
@jtk54 - PTAL
h/t to @rwinch for pointing this out!
> Validate redirect target to eliminate open redirect vulnerability

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
@jtk54, @riltsken, @ajordens  - FYI
> Properly extract attribute values, such as first and last name

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/AuthController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/AuthConfig.groovy
@jtk54 PTAL.
@anotherchrisberry, @ajordens, @cfieber:  Not sure what the logout experience would look like from the UI/UX perspective, but at least it's now possible.
@spinnaker/google-reviewers FYI
> Enable proper logout handler.

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/anonymous/AnonymousConfig.groovy
> Disable CSRF for anonymous config

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/google/GoogleDirectoryUserRolesProvider.groovy
Creates Google Directory service from json or env instead of p12. Note that the service account still needs to be given access with [domain wide delegation](https://developers.google.com/admin-sdk/directory/v1/guides/delegation#create_the_service_account_and_its_credentials) even if it is read from the environment. @ttomsu PTAL.
> Creates Google Directory service from json or env instead of p12.

- gate-web/config/gate.yml
> Adds default services.deck.baseUrl

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ImageController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ImageService.groovy
@duftler PTAL
@danielpeach FYI
> core: Restrict # of returned images

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
@cfieber or @ttomsu please tell me how to do this the right way...
> make session ttl configurable

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/UserRolesSyncer.groovy
using `keys` is [not recommended](http://redis.io/commands/keys)
replaces call with a scan which is surprisingly cumbersome via RedisTemplate
@ttomsu @jtk54 PTAL
> fix use of redis keys command

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ImageController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ImageService.groovy
- Specifically for passing <optional> tag filters
> Generically pass additional image query parameters to clouddriver

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/UserRolesSyncer.groovy
In theory username should be username in all cases except for github users.
Using username should fix the log out when using github oauth and UserRolesSyncer failure because it used email.
@ttomsu as we discussed on slack, PTAL.
> Use username instead of email in UserRolesSyncer.

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/anonymous/AnonymousConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PermissionService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/FiatService.groovy
Part 2 of https://github.com/spinnaker/gate/pull/262. Please review only the **last** commit.
@duftler @jtk54 @cfieber PTAL
@ajordens FYI
> Adds SAML, X509, and anonymous Fiat integration

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
Closes spinnaker/spinnaker#993
> Loosen SAML AttributeValue parsing

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ServerGroupService.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/ServerGroupServiceSpec.groovy
We've had a request to include "cluster" for some insight links internally at Netflix.
@ajordens any concerns here?
> include cluster in server group insight context

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GitHubProperties.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/github/client/GitHubClient.groovy
`@Path` can not be used for query params.
@ttomsu PTAL
cc @jvasallo
> Fix GitHub pagination and add more validations

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/Front50Service.groovy
- Updated Front50 application to use the new V2 API
> Front50 V2 application API

- build.gradle
@duftler @jtk54  @cfieber PTAL
> Gate: Bumps spinnaker-dependencies version

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy
- Wrap `pipelineService.save()` in a HystrixCommand
> Extract `error` from RetrofitError body if available

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ProjectService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/Front50Service.groovy
- Removed the try and catch. Now using the new method call to the API
> Remove the fallback handle of project API

- build.gradle
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CanaryController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/NetworkService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/hystrix/spectator/HystrixSpectatorPublisherCommand.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/hystrix/spectator/HystrixSpectatorPublisherThreadPool.groovy
- gradle/wrapper/gradle-wrapper.properties
fixes for spectator ValueFunction -> ToDoubleFunction
fixes for groovy 2.4 static compilation
> updates dependencies

- gate-web/config/gate.yml
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/BakeController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/BakeService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/RoscoService.groovy
> Add new entry-point to propagate bakery logs.

- build.gradle
@cfieber @jtk54 FYI
Adds /resolvedEnv endpoint
> spinnaker-deps bump

- build.gradle
- gate-web/gate-web.gradle
> Added stackdriver

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/StrategyController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/StrategyService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/Front50Service.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/PipelineControllerSpec.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/StrategyControllerSpec.groovy
- First pass at consolidating pipeline updates around `pipelines/{pipelineId}`
> Adding update pipeline endpoint

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/ExternalAuthTokenFilter.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuth2SsoConfig.groovy
Fixes startup issue reported by @skim1420 
@jtk54 FYI
> Make nested OAuthSSO adapter component conditional on outer component.

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/ExternalAuthTokenFilter.groovy
@jtk54 @skim1420  FYI
I logged in this time and confirmed it works.
> Stoopud NPEs

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/TaskController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/TaskService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaService.groovy
- endpoint to cancel a list of tasks by task ids
> Batch task cancelling

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
@jeyrschabu PTAL - this should fix the other exception we keep seeing in the logs
> propagate 404 status when pipeline is not found

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/EntityTagsController.java
@ajordens PTAL
Happy to add more context on the swagger bits once we're satisfied that the API is stable
> update entity tags via POST, set created/modified values

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CredentialsController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509Config.groovy
Also fixes incorrect Fiat permission.
Fixes spinnaker/fiat#123
@duftler @jtk54 PTAL
> Adds noop manager to standalone x509 config.

- halconfig/gate.yml
> Base gate halconfig

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/EntityTagsController.java
The `v2` orchestration work in `orca` current requires that an application name has been supplied.
FYI @jeyrschabu
> Parse application name from `entityId` and pass along to `orca`

- gate-web/gate-web.gradle
@jtk54 PTAL
@cfieber @ajordens FYI
> Fiat bump to add LDAP role source.

- Dockerfile
- Dockerfile.slim
- build.gradle
- cloudbuild.yaml
> Slim build & spinnaker gradle project bump

- gate-web/config/gate.yml
Resolves https://github.com/spinnaker/spinnaker/issues/1413
> Fix github OAuth support

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/AuthController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/ldap/LdapSsoConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServices.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PermissionService.groovy
@duftler @jtk54 @cfieber PTAL
@PerGon @danielpeach FYI
> Incorporate Fiat roles in /auth/user

- halconfig/gate.yml
> (halconfig) Update redis connection to use baseUrl

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/BatchEntityTagsController.java
Depends on https://github.com/spinnaker/orca/pull/1181
> add batchUpdate endpoint for tagging

- gate-web/config/gate.yml
> Swagger new active executions endpoint.

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/TaskService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaService.groovy
Corresponds with PR [#1188](https://github.com/spinnaker/orca/pull/1188) in Orca.
> Support `force` parameter for cancel pipeline endpoint in Orca

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/AuthConfig.groovy
@ttomsu can you give this a shot and verify it still allows basic auth as expected (via config)?
> fix(auth): make basic authentication configurable and opt-in

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/InstanceService.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/InstanceServiceSpec.groovy
* added account metadata to instance metadata map for use in insight
links.
> feat(instances): add more account metadata

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/Rate.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptor.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RedisRateLimiter.java
> feat(ratelimit): Add throttle metric counter, capacity details in throttle log msg

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy
> fix(ratelimit): Autowire metrics registry

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServices.groovy
> fix(authn): Print user info details when debugging is enabled

- build.gradle
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/Main.groovy
Removes static property init in Main since it is in kork-web now.
> fix(tls): tls updates from kork 1.89.0

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ServerGroupController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ServerGroupService.groovy
Corresponding PR for https://github.com/spinnaker/clouddriver/pull/1558
> feat(servergroups): send clusters param on /serverGroups

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/ldap/LdapSsoConfig.groovy
> fix(ldap): make LDAP login page come before the rest of auth config

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ExecutionsController.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaService.groovy
Allows querying by a pipelineConfigId to get recent executions
Depends on https://github.com/spinnaker/orca/pull/1293
> feat(executions): add endpoint to get executions by config id

- build.gradle
- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/commands/AbstractHystrixCommand.groovy
- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/commands/HystrixFactory.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/NetworkService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/aws/InfrastructureService.groovy
We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](http://www.spinnaker.io/docs/contributing-to-spinnaker).
When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.
Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a …
> chore(kork): fix compatibility with latest kork

- build.gradle
picks up latest frigga supporting ~ in detail in names
> chore(dependencies): update to latest spinnaker-dependencies

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaService.groovy
> feat(pipeline): add endpoint for evaluating pipeline expressions

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
Will now bubble up errors generated by orca's pipeline template module:
```json
{
"errors": [
{
"location": "configuration:stages.foo",
"message": "A configuration-defined stage should have either dependsOn or an inject rule defined",
"severity": "WARN"
}
],
"message": "Pipeline template is invalid",
"status": "BAD_REQUEST"
}
```
Decent way to go about this?
> fix(pipelinetemplate): Propagate pipeline template errors

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineTemplatesController.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineTemplateService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaService.groovy
> feat(api): Expose orca resolve Pipeline Template endpoint

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/filters/CorsFilter.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptor.java
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptorSpec.groovy
> fix(ratelimit): Ignore deck API requests

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptor.java
@spinnaker/netflix-reviewers FYI
> fix(ratelimit): Correctly log principal name

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptor.java
> feat(*): Set anonymous principal to x-ratelimit-app header if provided

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptor.java
> fix(ratelimit): Check user for anonymous email

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CertificateController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CertificateService.groovy
Depends on https://github.com/spinnaker/clouddriver/pull/1702
> feat(provider/amazon): Provide endpoints for the certificate provider in clouddriver

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
Fiat API disables this, but Gate constructs the Fiat retrofit interface itself, which didn't have this. When new role providers are added, it ends up breaking... pretty much everything.
> fix(fiat): Makes ObjectMapper not fail on unknown enum values.

- gate-web/config/gate.yml
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/V2CanaryController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CanaryConfigService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/KayentaCanaryConfigService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KayentaService.groovy
> feat(canary): v2 canary endpoints

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ServerGroupController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ServerGroupService.groovy
- Added a new endpoint to return an aggregated list of server groups
- Takes a list of applications as params
> feat(servergroups): Add server group endpoints for a list of applications

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineTemplatesController.java
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/PipelineTemplateControllerSpec.groovy
> feat(pipeline_templates) delete template operation

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/V2CanaryConfigController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/V2CanaryController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CanaryConfigService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/KayentaCanaryConfigService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KayentaService.groovy
> feat(canary): v2 canary delete endpoint

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/commands/AbstractHystrixCommand.groovy
- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/commands/ServerErrorException.java
- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/commands/ServiceUnavailableException.java
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/FunctionalSpec.groovy
- Updated to return a 503 when hystrix breaker is flipped
> chore(hystrix): Change to return a 503 instead of 429

- build.gradle
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
Depends on https://github.com/spinnaker/kork/pull/90
> feat(web): AuthenticatedRequest user origin extraction

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/V2CanaryController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KayentaService.groovy
> feat(canary-v2): adds canary judge endpoint

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineTemplatesController.java
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/PipelineControllerSpec.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/PipelineTemplateControllerSpec.groovy
Add users to both pipeline save & pipeline template crud operations.
> feat(web): Add user to save pipeline & pipeline template tasks

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/SearchController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/SearchService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/SecurityGroupService.groovy
* allows search clients to pass additional search/filter arguments to
the search endpoint via query parameters.
> feat(search): enhance searching capabilities

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ApplicationController.groovy
> feat(web): Filter applications by owner email

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/Front50Service.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/ApplicationServiceSpec.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/PipelineControllerSpec.groovy
@ajordens 
Depends on changes in https://github.com/spinnaker/front50/pull/268 - don't merge until this is merged.
> perf(web): don't refresh pipeline config on pipeline start

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/PipelineControllerSpec.groovy
Reverting to default behavior of refreshing all times except starting a pipeline. 
@ewiseblatt @ajordens PTAL
> fix(web): restoring default behavior to pipeline refresh

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/V2CanaryController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KayentaService.groovy
> feat(v2-canary): add kayenta credentials endpoint

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/V2CanaryController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KayentaService.groovy
> feat(v2-canary): canary result endpoints

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ServerGroupManagerController.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ServerGroupManagerService.java
> feat(core): server group manager controller

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/AuthController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ServerGroupController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ServerGroupService.groovy
Depends on https://github.com/spinnaker/clouddriver/pull/2114
> feat(core/serverGroups): Get a list of servergroups by name

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/ldap/LdapSsoConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/ldap/LdapSsoConfigurer.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509Config.groovy
Similar to #460, but for LDAP and x509.
> feat(x509) Allow x509 and LDAP to be used together

- build.gradle
- new kork (strip out empty roles from `User`)
> chore(dependencies): bump spinnaker-dependencies to 0.132.0

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ecs/EcsClusterController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/EcsClusterService.groovy
feat(provider/ecs): Added ECS cluster controller + service
Please note that this is about ECS clusters (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_clusters.html) and not clusters in the Spinnaker sense
@cfieber @ajordens @robzienert @dkirillov
> feat(provider/ecs): Added ECS cluster controller + service

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/RoleController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/RoleService.groovy
feat(provider/ecs): Added role controller & service
@cfieber @ajordens @robzienert @dkirillov
> feat(provider/ecs): Added role controller & service

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
Fixes https://github.com/spinnaker/spinnaker/issues/2220
> fix(pipelines): allow utf-8 characters in pipeline fields

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ecs/EcsCloudMetricController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/EcsCloudMetricService.groovy
feat(provider/ecs): Added cloud metrics controller + service
@cfieber @ajordens @robzienert @dkirillov
> feat(provider/ecs): Added cloud metrics controller + service

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ApplicationController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ExecutionHistoryService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaService.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/FunctionalSpec.groovy
this pipes an expand query param for execution history to orca.  see https://github.com/spinnaker/orca/pull/2061
> feat(core): add expand query param to execution history

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ServerGroupService.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/ServerGroupServiceSpec.groovy
This is the same functionality available in the instanceService, allows us to reference account detail variables such as environment
> fix(web): allow account details to be referenced in server group insights

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/EntityTagsController.java
> fix(entitytags): Explicitly `toLowerCase` when looking up entity tags by id

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaService.groovy
This call is danger-town.
@ajordens FYI
> chore(*): Remove OrcaService.all() call

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/filters/FiatSessionFilter.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/AuthConfig.groovy
This PR is an attempt to fix https://github.com/spinnaker/spinnaker/issues/2694 by introducing the ability to turn off this filter.
> feat(authz): Add ability to disable Fiat session filter.

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PermissionService.groovy
> feat(permission): hystrix wrappers for permission service calls

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PermissionService.groovy
> fix(permission): missing execute on hystrix wrappers

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ExecutionsController.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/WebhookController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/WebhookService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/EchoService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaService.groovy
Also related:
https://github.com/spinnaker/orca/pull/2292
https://github.com/spinnaker/echo/pull/277
> feat(triggers): Add endpoint to search for pipeline executions and change webhooks endpoint to return a map.

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/filters/FiatSessionFilter.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/AuthConfig.groovy
only inject fiat session filter in filter chain if it is enabled
> feat(auth): conditional fiat session filter

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/iap/IAPAuthenticationFilter.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/iap/IAPSsoConfig.java
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/iap/IAPAuthenticationFilterSpec.groovy
By not throwing errors in the filter prematurely, this change allows the
AuthConfig's permitted paths to pass through, such as `auth/user`. This
delegates authentication error handling to the `FilterSecurityInterceptor`
itself. Also extended the filter as a `OncePerRequestFilter`.
> fix(authn/iap): Change filter to respect AuthConfig permitted paths.

- gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/ProxyController.kt
It's now quite easy to add additional http methods but I stopped short
of adding any more.
We may want to offer an ability to restrict http methods per proxy
configuration.
> feat(web): Added generic proxy support for `POST` requests

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineTemplatesController.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineTemplateService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/Front50Service.groovy
Pretty simple thing here, just returns pointers to the client of dependent pipelines of any given template.
> feat(pipeline_template): Expose dependent pipelines endpoint

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
- gate-web/gate-web.gradle
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ArtifactController.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ArtifactService.java
Add `PUT artifacts/fetch` endpoint to enable artifact previewing in the UI.
> feat(artifacts): Add API to fetch artifact contents

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ecs/EcsSecretsController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/EcsSecretService.groovy
Addresses spinnaker/spinnaker#3339
Related to spinnaker/clouddriver#2998
> feat(ecs): Add support for retrieving available Secrets Manager secrets

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RedisRateLimitPrincipalProvider.java
Previously could have happened multiple times within the same request.
Also added a kill switch based on the presence of `app:deck` in the
`rateLimit:enforcing` set.
> fix(web): Avoid unnecessary calls to `jedisPool.getResource()`

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/ApplicationServiceSpec.groovy
Resolves https://github.com/spinnaker/spinnaker/issues/3425. @ezimanyi's explanation of the problem in that issue sounds right to me.
@ajordens please let me know if you think this should be reverted as is or whether the behavior you wrote here should be feature-flagged.
I'll cherry-pick whatever we decide to do into the 1.10.x branch.
> Revert "feat(web): Serve `/applications` out of the recent cache (#603)"

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/ApplicationServiceSpec.groovy
Companion to this PR: https://github.com/spinnaker/gate/pull/629
> fix(web): poll unrestricted clouddriver applications endpoint 

- build.gradle
- gate-web/gate-web.gradle
- gradle/buildViaTravis.sh
- gradle/init-publish.gradle
- gradle/installViaTravis.sh
- gradle/wrapper/gradle-wrapper.properties
Removes spring boot gradle plugin
Ref: https://github.com/spinnaker/spinnaker/issues/2844
> chore(builds): Introduces composite builds via gradle plugin

- README.md
- gate-web/gate-web.gradle
- gradle.properties
- settings.gradle
Closes https://github.com/spinnaker/spinnaker/issues/3498
> feat(build): Introduces modular builds for Gate

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/iap/IAPAuthenticationFilter.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/iap/IAPSsoConfig.java
> fix(iap/basicauth): Configure the BasicAuth auth manager for IAP. (#662)

- build.gradle
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy
> fix(dependencies): Fix compile static error while bumping spinnaker-deps

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ExecutionsController.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaService.groovy
Corresponding PR for https://github.com/spinnaker/orca/pull/2522
> feat(pipelines): add executionIds, expand params to /pipelines endpoint

- gate-web/config/gate.yml
Related to https://github.com/spinnaker/spinnaker/issues/3787
> chore(swagger): Included /projects/ endpoints for use in spin-cli.

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ArtifactController.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ArtifactService.java
issue: spinnaker/spinnaker#3284
> feat(artifacts): Add support for helm/chart artifacts

- gate-x509/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsService.groovy
Parity with `saml.requiredRoles`.
Defaults to `emptyList()` and should have no impact on existing users
of x509 certificates.
> feat(x509): Support for `x509.requiredRoles`

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ServiceBrokerController.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ServiceBrokerService.java
This is for the polling the status of Deploy Service and Destroy Service in Orca.
spinnaker/spinnaker#3637
> feat(cf): Expose service-specific information

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/V2PipelineTemplatesController.java
Port of https://github.com/spinnaker/gate/pull/719 to 1.12.x.
> fix(MPTv2): Wait for downstream Orca ops for v2 MPTs.

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ArtifactoryController.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/IgorService.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/basic/AbstractAuthSpec.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/ldap/LdapAuthSpec.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/swagger/GenerateSwagger.groovy
> feat(core): Add support for an Artifactory Trigger

- gate-iap/src/main/java/com/netflix/spinnaker/gate/security/iap/IapAuthenticationFilter.java
- gate-iap/src/main/java/com/netflix/spinnaker/gate/security/iap/IapSsoConfig.java
- gate-iap/src/test/groovy/com/netflix/spinnaker/gate/security/iap/IapAuthenticationFilterSpec.groovy
* fix(iap): Add a clock skew flag for IAP issue time and expiration time checks.
* fix(iap): Rename IAPSecurityConfigProperties to IapSecurityConfigProperties.
> fix(iap): Add a clock skew flag for IAP issue time and expiration time checks. (#766)

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/filters/FiatSessionFilter.groovy
- gate-saml/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
- gate-x509/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsService.groovy
- gate-x509/src/test/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsServiceSpec.groovy
> feat(auth): Ensure that a legacy fallback is not cached beyond a request

- gate-web/gate-web.gradle
Prereq for spinnaker/kork#273 merge
> chore(dependencies): ensure direct dependency on kork-secrets-aws

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
Existing applications without EXECUTE will continue to use READ for check using https://github.com/spinnaker/fiat/pull/390
Part of spinnaker/spinnaker#3554
> feat(authz): Use EXECUTE instead of READ for triggering pipelines.

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ConcourseController.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/IgorService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaService.groovy
> feat(stages): Add API to support Concourse stage

- build.gradle
- gate-proxy/src/main/kotlin/com/netflix/spinnaker/config/ProxyConfiguration.kt
- gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/ProxyController.kt
* chore(*): Apply codestyles 
Most files were picked up by applyin to the base project in the prior PR, so it's just these two kotlin files.
* chore(*): Turn on codestyle enforcement
> chore(*): Apply codestyles 

- build.gradle
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/BakeService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/RoscoServiceSelector.java
- Added RoscoServiceSelector to find services by location/region
- Make bakeService use the roscoServiceSelector
- Refactor OrcaServiceSelector criteria instantiation
> feat(bakery): Add rosco service selector

- gate-web/gate-web.gradle
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy
echo: https://github.com/spinnaker/echo/pull/563
orca: https://github.com/spinnaker/orca/pull/2945
> fix(pipelines): V2 trigger API now correctly returns an execution ref

- build.gradle
- gate-bom/gate-bom.gradle
- settings.gradle
This simplifies dependency resolution downstream
> feat(gate-bom): publish gate-bom

- gate-oauth2/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuth2SsoConfig.groovy
- gate-oauth2/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServices.groovy
- gate-oauth2/src/test/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServicesSpec.groovy
If present in userAuthentication details, extract roles and use for login
> feat(oauth2): support roles from userInfo mapping

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/DeliveryController.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
- gradle.properties
upsert, get, and delete a keel managed resource through gate.
> feat(md): crud of resources through gate

- gate-core/gate-core.gradle
- gate-core/src/main/groovy/com/netflix/spinnaker/gate/config/MultiAuthSupport.java
This is a cherry pick https://github.com/spinnaker/gate/pull/844 for release-1.14.x
> fix(auth): Enable auth to all connectors except API port (1.14.x)

- gate-core/gate-core.gradle
- gate-core/src/main/groovy/com/netflix/spinnaker/gate/config/MultiAuthSupport.java
This is a cherry pick #844 for release-1.15.x
@ajordens ^ Sorry missed 1.15 earlier.
> fix(auth): Enable auth to all connectors except API port (1.15.x)

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaService.groovy
Exposing the endpoint from https://github.com/spinnaker/orca/pull/3073
> feat(expressions): exposing expression eval by stage endpoint

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
Exposing endpoints from https://github.com/spinnaker/keel/pull/356
Also a spelling fix.
> feat(keel): app-specific endpoints

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/HistoryController.java
> feat(keel): reflect change in how resource history works in Keel API

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/HistoryController.java
Changing this to a map (sorry Erik) until we have some stability in this API.
> chore(history): maps not typed

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/NexusController.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/IgorService.groovy
> fix(nexus): add nexus repo names endpoint

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
Updating the diff endpoints to accept both json and yaml.
Updating to new spring `@GetMapping` etc.
> fix(md): diff endpoint accepts yaml

- README.md
> chore(builds): Need an edit to test a new step in the build process

- README.md
> Revert "chore(builds): Remove the temp line in README"

- README.md
Reverts spinnaker/gate#946
GCB has some funky interaction with GCS.
> chore(builds): Revert 2: Revert Harder

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CapabilitiesController.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaService.groovy
Expose expression capability endpoints defined in https://github.com/spinnaker/orca/pull/3273
> feat(expressions): add ability to query expression capabilities

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
> fix(md): fix return type of deliver-config diff

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaService.groovy
This exposes the EP defined in orca as part of https://github.com/spinnaker/orca/pull/3286
> feat(expressions): add evaluateVariables endpoint

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
> fix(md): fix post request

- .github/workflows/pr.yml
see: https://github.com/actions/checkout/blob/master/README.md
> chore(build): GitHub Actions checkout@v2

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
Forgot to expose this in gate.
> feat(md): delete delivery configs

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/NotificationService.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/NotificationServiceSpec.groovy
I overlooked that in the previous PR. 😞
> fix(notifications): Fix wiring of OkHttpClient

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/AwsCodeBuildController.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/IgorService.groovy
depend on https://github.com/spinnaker/igor/pull/635
> feat(codebuild): Add API to call igor to list projects

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/Front50Service.groovy
- gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/deck/DeckPluginCache.kt
- gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/publish/PluginBinaryController.kt
Retrofit is being a huge pain in the ass when it comes to uploads. We need to upgrade to Retrofit 2, but I'm not going to do that as part of this work.
> fix(plugins): Upload plugins with raw OkHttpClient

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CiController.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CiService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/IgorService.groovy
Adding an entry point in gate to support CI related calls, which eventually will be used by deck.
Igor implementation is here: https://github.com/spinnaker/igor/pull/641
> feat(ciView): Add CI entry point for CI view feature

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
> fix(spring): Add flag to request logger

- gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/deck/DeckPluginCache.kt
- gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/deck/DeckPluginService.kt
- gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/deck/DeckPluginsController.kt
- gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/publish/PluginBinaryController.kt
- gate-plugins/src/test/kotlin/com/netflix/spinnaker/gate/plugins/deck/DeckPluginCacheTest.kt
- gate-proxy/src/main/kotlin/com/netflix/spinnaker/config/ProxyConfiguration.kt
- gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/ProxyController.kt
ktlint picked this up when I was trying trying to change unrelated file...
> chore(formatting): fix formatting on some files

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
Update to the api for this https://github.com/spinnaker/keel/pull/942
> fix(md): update constraint endpoints

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy
This reverts commit 8f15de434dcf88a86d233d894d228e46e9d46bd2.
> Revert "fix(etag): removing etag filter (#1123)"

- gate-x509/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsService.groovy
Adds retry support, as is present in other implementations.
> fix(fiat): Add retries around x509 permissionService login calls

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/model/manageddelivery/EnvironmentArtifactPin.java
- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
Exposing pinning apis through gate. Apis from https://github.com/spinnaker/keel/pull/978
> feat(md): add pin apis

- gate-plugins-test/gate-plugins-test.gradle
- gate-plugins-test/src/main/kotlin/com/netflix/spinnaker/gate/plugins/GateApiExtension.kt
- gate-plugins-test/src/main/kotlin/com/netflix/spinnaker/gate/plugins/GatePlugin.kt
- gate-plugins-test/src/test/kotlin/com/netflix/spinnaker/gate/plugins/test/GatePluginsFixture.kt
- gate-plugins-test/src/test/kotlin/com/netflix/spinnaker/gate/plugins/test/GatePluginsTest.kt
- gate-plugins-test/src/test/resources/gate-plugins-test.yml
- gate-web/gate-web.gradle
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/Main.groovy
- settings.gradle
Setting this to "do not merge" until we have pulled in these Gradle changes -- spinnaker/spinnaker-gradle-project#121
Without that, these tests fail when pulling in the existing dependencies in the spinnaker.project plugin.
> feat(plugins): Add gate-plugins-test module

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
Exposing https://github.com/spinnaker/keel/pull/1050 through gate.
> feat(md): get config by app endpoint

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/model/manageddelivery/EnvironmentArtifactVeto.java
- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
Expose export artifact endpoint.
Fix veto endpoint to actually serialize the body
> feat(md): export artifact from cluster, fix veto

- .github/workflows/build.yml
Testing this out as a one off before applying to all repos.
> fix(builds): Run branch build on release branches

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
Exposes https://github.com/spinnaker/keel/pull/1101
> feat(md): delete delivery config by application

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
Was reading through how some of the security autowiring works, and found a minor fix to this comment.
> style(core): Minor clarification to comment

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
Counterpart to https://github.com/spinnaker/keel/pull/1143.
> fix(managed-delivery): Fix unpin API

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/DataController.groovy
Prior to this PR, the `Content-Type` was defaulting to `text/html` which
rendered correctly in the browser but appeared to cause problems with `deck`.
Given a narrow set of use-cases, these endpoints now default to returning
`application/json` and use the `OutputStream` from `HttpServletResponse`
rather than re-creating a new one and copying bytes.
> fix(web): Default `Content-Type` within `DataController`

- gate-integrations-gremlin/gate-integrations-gremlin.gradle
- gate-integrations-gremlin/src/main/java/com/netflix/spinnaker/config/GremlinConfig.java
- gate-plugins-test/src/test/resources/gate-plugins-test.yml
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/PagerDutyConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/SlackConfig.java
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/ldap/LdapAuthSpec.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/swagger/GenerateSwaggerSpec.groovy
- gate-web/src/test/resources/basic-auth.properties
- gate-web/src/test/resources/gate-test.yml
Converting it to use new client provider
> fix(misc): Move to new client provider for building retrofit client

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/model/manageddelivery/EnvironmentArtifactVeto.java
propagating comment through from https://github.com/spinnaker/keel/pull/1264
> feat(md): add comment to mark as bad

- gate-web/gate-web.gradle
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/Main.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GraphQLConfig.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/graphql/RootMutationResolver.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/graphql/RootQueryResolver.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/graphql/model/EmptyNode.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/graphql/model/Node.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/graphql/resolvers/EmptyNodeResolver.java
- gate-web/src/main/resources/graphql.properties
- gate-web/src/main/resources/graphql/root.graphqls
The start of GraphQL support.
I'll be happy to help build out the initial data fetchers and what have you once we've identified what to tackle first / have Deck wired up to talk to this endpoint.
> feat(web): Introduce GraphQL endpoint

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/DefaultProviderLookupService.groovy
Looks like an extra z slipped into a recent PR (spinnaker/gate#1237); removing it.
> fix(gate): Remove extraneous z

- gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/ProxyController.kt
Submitting a DELETE (which permits a request body) with a null contentType resulted in unlogged NPEs
> fix(proxies): handle null bodies and log exceptions

- gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/deck/DeckPluginCache.kt
- gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/deck/DeckPluginConfiguration.kt
- gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/deck/DeckPluginService.kt
- gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/deck/DeckPluginsController.kt
- gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/web/info/PluginInfoController.kt
- gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/web/publish/PluginPublishController.kt
- gate-proxy/src/test/kotlin/com/netflix/spinnaker/gate/controllers/ApiExtensionControllerTest.kt
- gradle.properties
This includes updates to google-java-format and ktlint, so requires some
formatting changes. These were made with a simple `./gradlew spotlessApply`.
> chore(spotless): upgrade spinnaker gradle plugin

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
Related to https://github.com/spinnaker/orca/pull/3841
> feat(pipeline): populate 'staleCheck' in orca savePipeline task

- build.gradle
- gate-core/src/main/groovy/com/netflix/spinnaker/gate/config/MultiAuthSupport.java
- gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/ApiExtensionController.kt
- gradle.properties
- gradle/kotlin-test.gradle
- gradle/kotlin.gradle
-- Kork autobump PR's are failing due to kotlin version mismatches between Kork and Gate.
> fix(misc): Upgrade to kotlin 1.4 to match with kork kotlin version

- gate-api/src/main/java/com/netflix/spinnaker/gate/api/extension/ProxyConfig.java
- gate-api/src/main/java/com/netflix/spinnaker/gate/api/extension/ProxyConfigProvider.java
- gate-proxy/src/main/kotlin/com/netflix/spinnaker/config/ProxyConfiguration.kt
- gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/Proxy.kt
- gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/ProxyController.kt
This PR supports bundling of proxy configuration alongside the
plugins that require it.
> feat(proxy): A simple extension point around `ProxyConfig`

- gate-web/gate-web.gradle
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/RateLimiterConfig.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/RateLimiterConfiguration.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingFilter.java
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingFilterSpec.groovy
- gate-x509/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsService.groovy
This PR also allows for the filter to be ordered pre/post the
spring security filter chain.
> feat(web): Convert RateLimitingInterceptor into HttpFilter

- gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
Follow-up to https://github.com/spinnaker/keel/pull/1561 to enable the `maxArtifactVersions` parameter in Gate.
> feat(managed-delivery): Add maxArtifactVersions param to GET /application

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/filters/RequestSheddingFilter.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingFilter.java
Just closing out some small todo's as part of converting these two into filters that
run ahead of the security filter chain and endpoint interceptors.
In the future I could see collapsing what `MetricsInterceptor` is currently doing into
the `RequestLoggingFilter`. Given that these two are used differently between `gate`
and the other internal services, I've left that as a later exercise.
> fix(web): Emit a `controller.invocations` metric whenever a request is limited or shed

- gate-saml/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
Added configuration options to allow sorting of roles and disabling of lowercasing of role names.
Our SAML provider (Okta) doesn't send nicely sorted SAML `memberOf` in the assertions, this allows us to configure it gate-side to sort in a more natural way. Also added a flag to disable the `toLowercase()` processing of roles.
> feat(authn/saml): Allow role sorting and lowercase configuration

- gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/IgorService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CiController.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CiService.java
This is the entry point for deck to get the data needed for the builds view (spinCI) in the UI.
We have two endpoints:
1. get all builds
2. get build's output.
The actual implementation is done in igor (see https://github.com/spinnaker/igor/pull/904 for reference )
> feat(ci): adding build output hook

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/BuildService.groovy
- use controller where possible
> fix(builds): Improve error message formatting and wording

- gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
> feat(md): expose nicer veto endpoints

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
> chore(api): fix api docs

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/model/manageddelivery/OverrideVerificationRequest.java
- gate-core/src/main/groovy/com/netflix/spinnaker/gate/model/manageddelivery/RetryVerificationRequest.java
- gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
New features for Managed Delivery
> expose override and retry verification endpoints 

- gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
Exposes a new `/managed/reports/onboarding` endpoint for Managed Delivery.
> feat(managed-delivery): Expose reports API

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/model/manageddelivery/RetryVerificationRequest.java
- gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
exposing https://github.com/spinnaker/keel/pull/1824/files
> feat(md): add environments api

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/model/manageddelivery/OverrideVerificationRequest.java
- gate-core/src/main/groovy/com/netflix/spinnaker/gate/model/manageddelivery/RetryVerificationRequest.java
- gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/KeelService.java
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
corresponding fix to https://github.com/spinnaker/keel/pull/1837
> fix(md): remove slashy var from url param

- gate-core/src/main/groovy/com/netflix/spinnaker/gate/model/manageddelivery/Environment.java
> fix(md): verifyWith is a list of maps..

- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/BatchEntityTagsController.java
Also change the default from "ad-hoc" (which is an invalid application name) to "adhoc"
> feat(tags): let callers of /batch/tags specify an application

- gate-bom/gate-bom.gradle
- gate-core/gate-core.gradle
- gate-iap/gate-iap.gradle
- gate-oauth2/gate-oauth2.gradle
- gate-plugins/gate-plugins.gradle
- gate-saml/gate-saml.gradle
- gate-web/gate-web.gradle
- gate-x509/gate-x509.gradle
- gradle.properties
> chore(deps): update fiat to 1.27.0, use new maven coordinates

- gate-oauth2/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServices.groovy
This PR allows extension projects to define a custom function for extracting groups.
This enables the ability to extract groups from the access token or the user object in addition from being able to extract groups from embedded sub-objects where as the current impl only allows the fetching of groups from root keys in the objects.
I testing this logic locally via defining the following config in my extension project
```java
...
...
@Configuration
public class ArmoryCloudIamConfig {
...
...
@Bean
@Qualifier("spinnaker-oauth2-group-extractor")
public BiFunction<String, Map, List<String>> armoryCloudGroupExtractor(
ArmoryCloudIamPrincipalService principalService) {
return (accessToken, userDetails) -> {
var principal = principalService.extractAndVerifyArmoryCloudPrincipal(accessToken); …
```
> feat(oauth2): allow extension projects to define a custom function for extracting groups

- gate-web/gate-web.gradle
This change makes the project compatible with Gradle 7
> chore(build): Gradle 7 compatibility

- gate-web/src/test/groovy/com/netflix/spinnaker/gate/config/RedisTestConfig.groovy
to use the hostname and JedisPool from EmbeddedRedis
> refactor(web/test): update RedisTestConfig

- gate-oauth2/gate-oauth2.gradle
- gate-oauth2/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServices.groovy
- gate-oauth2/src/test/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServicesSpec.groovy
- gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
- gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/PipelineControllerSpec.groovy
Retrofit2SyncCall.execute() calls were missing at a couple of places . So added tests to demonstrate the issue and then made the fixes.
> fix(retrofit2): retrofit2 bug fixes
