gate-core/gate-core.gradle
gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/commands/AbstractHystrixCommand.groovy
gate-web/config/hystrix.properties
gate-web/gate-web.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/Main.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy

- Removed the hardcoded 60s default timeout (similarly replaced in hystrix.properties)
- Bumped hystrix to 1.4.20
- Added specific hystrix wrappers around Cloud Driver and Front50 in ApplicationService (should be more resilient around failures to only one of CD or F50)

Hystrix properties can now be overridden in `hystrix.properties`

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SAMLSecurityConfig.groovy

Currently, if SAML is enabled, all `OPTIONS` requests require authentication. This causes issues with preflight requests. These requests are not supposed to be sent with credentials, so the backend should not expect them to be.

Allow OPTIONS requests for all endpoints when SAML is enabled

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/retrofit/UpstreamBadRequest.java
gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/commands/AbstractHystrixCommand.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy

- Will be extracted out into kork-hystrix

Pass any 429's through without triggering any Hystrix events

---

gate-web/gate-web.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/BuildController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/BuildService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/IgorService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/BuildControllerSpec.groovy

Fixes: https://github.com/spinnaker/spinnaker/issues/605
Depends on: https://github.com/spinnaker/igor/pull/42
This updates the Igor endpoints to go along with the changes in https://github.com/spinnaker/igor/pull/42. This also updates the actual gate endpoints to move all job names to the end of the URLs. I've also added a version to the front of the Jenkins API endpoints to facilitate future changes.
Gate URL changes:
| Old URL                                                  | New URL                                                    |
|----------------------------------------------------------|------------------------------------------------------------|
| /builds                                                  | /v2/builds                                                 |
| …

Update endpoints to support Jenkins folder plugin

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/SubnetController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/aws/InfrastructureService.groovy

Deprecate existing getSubnets() entry-point in aws.InfrastructureService and have it delegate to allByCloudProvider('aws').
Should be no breaking changes for any caller.

Add new SubnetController with allByCloudProvider() entry-point.

---

gate-web/gate-web.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/client/OAuth2LoginAuthenticator.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/userdetailsservice/SpinnakerUserProvider.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/userdetailsservice/google/GoogleDirectoryUserProvider.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/userdetailsservice/google/GoogleDirectoryUserProviderConfig.groovy

This PR adds the interface to acquire user groups/user information for authN/Z, as well as the implementation that ties into the Google Directory Groups API. The interface currently requires an access token to hit the appropriate APIs to gather the user information, but this can be refactored if need be. @ttomsu @ajordens PTAL.

Adds 'UserProvider' interface and Google Directory implementation.

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ProjectService.groovy

If there are no projects configured, there won't be an `embedded` property, so we end up with a NPE.
It might be fixing this on the producer (front 50) - couple of ways to do that are outlined here: http://stackoverflow.com/questions/30286795/how-to-force-spring-hateoas-resources-to-render-an-empty-embedded-array

guard against no projects present

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/SpinnakerUser.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/client/OAuth2SsoConfig.groovy

This uses the @AuthenticationPrincipal annotation to nicely pull the custom user out of the `SecurityContextHolder`. Additionally, this PR eliminates the exposure of the access token to the user himself, because it seemed foolish to expose that. 
@jtk54 @rwinch PTAL.

Makes /user endpoint return a Kork user, instead of the framework's UsernamePasswordTokenServices object.

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/UserController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationProvider.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509Config.groovy

@jtk54 @rwinch PTAL.
I haven't looked, but hopefully Boot 1.3 adds in the ability to override a few hard coded classes in the `http.x509` configurer.

Re-enable X509 authentication

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/AuthController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/SpinnakerUser.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/client/OAuth2SsoConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509Config.groovy

@jtk54 PTAL
@rwinch, @ajordens FYI

Multi-auth with X509 and OAuth2

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfigurer.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509Config.groovy

Finished up the TODO items in https://github.com/spinnaker/gate/pull/208, specifically:
* Hooks in the roles/groupsMemberships that were previously being extracted
* Adds in user roles provider support
* Multi-auth support (aka SAML + X509)
This should mean that only small configuration changes are necessary for any existing installation (including NFLX)
@spinnaker/google-reviewers FYI

Multi-auth with SAML, NFLX user role extraction from the assertion.

---

gate-web/config/gate.yml

This PR adds a template with some known values for Google and Azure oauth providers. Users can create `gate-googleOAuth.yml` or `gate-azureOAuth.yml` files in their `~/.spinnaker/` config directories that simply specify the clientID and client secret, like so:
```
spring:
oauth2:
client:
clientId: my-client-id
clientSecret: my-client-secret
```
To pick up this profile at runtime, invoke  
```
$ ./gradlew -Dspring.profiles.active="local,googleOAuth"
```
@rguthriemsft @scotmoor @spinnaker/google-reviewers

Adds spring profile templates for Google and Azure OAuth providers.

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/DefaultProviderLookupService.groovy
gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/ProviderLookupService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ClusterService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ImageService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/InstanceService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/JobService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/LoadBalancerService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/NetworkService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/SecurityGroupService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ServerGroupService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/InstanceServiceSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/ServerGroupServiceSpec.groovy

though most of these are read operations, in the event of bad data or a bug in one cloud provider, we shouldn't circuit break across others

segment hystrix command keys by cloud provider

---

gate-web/gate-web.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy

Pulls in M2 release of SAML DSL library where I've added the switch to disable discovery.
@jtk54 PTAL.
@riltsken - Please take this PR for a spin to see if it gets around the issues you were hitting.

Disables SAML discovery in order to use SSO flow

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/AuthConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/UserRolesProvider.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/UserRolesSyncer.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/google/GoogleDirectoryUserRolesProvider.groovy

Added periodic check to invalidate session if user groups change. Invalidating the session will cause the user to re-auth and re-sync the groups, which is much safer and cleaner than updating the groups for a few reasons:
* Updating groups could allow the user to have unnecessary permissions for approximately a session.
* There is a different `Authentication` object for each of {OAuth2, x509, SAML}, updating which results in a lot of unnecessary duplicated code for something that is not incredibly secure.
* Since we now prompt to re-auth from Deck if the session is expired, invalidating the session does not cause the UX to suffer.
Should we reduce the period of when the re-auth checks happen in Deck? As it stands currently, a user might have up to 10 min of unsaved work with no session in …

Auth: added check to invalidate session if user groups change.

---

gate-web/gate-web.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/UserRolesSyncer.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/redis/EmbeddedRedis.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/rolesprovider/UserRolesSyncerSpec.groovy

Added unit tests and EmbeddedRedis testing tools as well. Version changed in https://github.com/spinnaker/gate/pull/223. This should be the last change before we can test and merge authentication into master. @ttomsu PTAL. @anotherchrisberry FYI.

Updated Syncer to use new session-data-redis version.

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CanaryController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CanaryService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/MineService.groovy

Bring back interfaces to mine service to enable experimentation around alternate ACA sources.
Tested with service.mine.enabled true and false with no issues

Reintroduce canary API in gate

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuth2SsoConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/UserRolesProvider.groovy

Generify the parameter name of `UserRolesProvider.loadRoles` to `userId` .
OAuth provider should use `username` as `userId` but other Authent systems still use `email`.
OAuth provider user mapping should define `username` : Google use `email` but Github OAuth use `login` because it' the input to get the memberships for a user.
@ttomsu PTAL .
I plan to do another PR to create a `GitHubTeamsUserRolesProvider` based on `GoogleDirectoryUserRolesProvider`

OAuth load roles from username

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/RootController.groovy

The main use case of this controller is to support the case when a user:
1. logs into his SAML provider
1. Clicks the Spinnaker application
1. SAML provider sends login request to `/saml/SSO`, logging in the user.
1. SAML library sends redirect to gate's root
1. This root controller redirects to Deck.
@jtk54 - PTAL
@ajordens @amanya FYI

Adds root controller to redirect to Deck's main page

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/AccountsService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CredentialsService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/AccountsServiceSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/CredentialsServiceSpec.groovy

@lwander PTAL, @duftler FYI
Warning: this is a hack. Before my auth changes went in, `AuthenticatedRequest.getSpinnakerUser()` returned null, so requests to the `CredentialsService` would always return all accounts without required group membership.
After the auth changes, `AuthenticatedRequest.getSpinnakerUser()` returned a Kork User that represented an anonymous user with `allowedAccounts: []`. This basically caused the credentials endpoint to become useless for anonymous users. 
This PR adds tests for the AccountsService that was added a while ago and wasn't tested.
Tested with anonymous config and confirmed an instance could be deleted (aka mutating calls work).

Quick and dirty fix for anon auth not returning credentials

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/AuthController.groovy

- This supports a situation where deck is available under http/https

Only check host and port when validating deck redirect

---

build.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/anonymous/AnonymousConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuth2SsoConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/anonymous/AnonymousConfigSpec.groovy

@ajordens @cfieber @jtk54 @duftler PTAL
Tests won't pass until https://github.com/spinnaker/kork/pull/40 is merged and released.

Makes anonymous principal's allowedAccounts updated periodically

---

gate-web/gate-web.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GitHubConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GitHubProperties.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/github/GithubTeamsUserRolesProvider.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/github/client/GitHubClient.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/github/client/GitHubMaster.groovy

Use GitHub teams to provide UserRoles.
To restrict to a whole organization : set requiredGroupMembership as the
organization.
To restrict to teams : set requiredGroupMembership as the teams slug.
The `access_token` configured needs the `org:read` grant.
@ttomsu @jtk54 PTAL. Currently the team membership is done by many calls to GitHub API and it could be replaced by a single call to https://developer.github.com/v3/orgs/teams/#list-user-teams but it needs the `access_token` of the current authenticated user.
EDIT: if `loadRoles` is a batch call to `loadRole` the call using the current authenticated user `access_token` cannot be used. So this implementation might be the final one.

GitHub Teams UserRoles provider

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy

Thanks to @johntheodore for bringing up this issue.
This PR allows a SAML user to use an external proxy to terminate SSL connections while running Gate in HTTP mode. The jist is you have to override `redirectHostname` and `redirectBasePath` to get the exact URL the IDP will use when contacting Gate. In the case of Google's click to deploy image, this Gate URL is `https://localhost:9000/gate/saml/SSO`, so the SAML config would include:
```
saml:
redirectHostname: localhost:9000
redirectBasePath: /gate
```
I included the protocol in the changes because someone may want that in the future and we might as well do it now too.
@cfieber @ajordens @jtk54 @duftler PTAL

Make SAML service provider protocol and basepath configurable

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy

Since this field is referenced directly in the superclass, setting a private field on the subclass doesn't do anything.

set maxInactiveIntervalInSeconds via setter

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/AuthController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/UserRolesSyncer.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/rolesprovider/UserRolesSyncerSpec.groovy

Added on-demand endpoint to refresh granted user roles. Also renamed the sync function as well. Seemed weirdto export 'syncUserGroups' from a 'UserRolesSyncer'. @ttomsu PTAL.

Added on-demand endpoint to refresh granted user roles.

---

build.gradle

Also cleans up spring-boot / spring-framework versions, we had
transitively pulled in a newer boot but were force downgrading
spring, this just officially revs the project up to 1.2.8.RELEASE
of boot and the corresponding 4.1.9.RELEASE of spring
spinnaker-dependencies 0.42.0 brings in kork 1.66.0 which enables a client cert blacklist for SSL client authentication

Update to spinnaker-dependencies 0.42.0

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/github/GithubTeamsUserRolesProvider.groovy

The exception is not needed. Added the userName in the log message.
@ttomsu PTAL

GitHub AuthN : change log message when user not a member of org.

---

gate-web/gate-web.gradle

This change will fix problems where logrotate ignores
/etc/logrotate/gate due to 'bad file mode.'
For Spinnaker issue [#904](https://github.com/spinnaker/spinnaker/issues/904)

Update logrotate file permissions

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ApplicationServiceSpec.groovy

Makes scripting a little more durable, as users can trigger pipelines by ID without worrying about them being renamed.
@ajordens WDYT?

(core) allow pipeline triggering by id or name

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy

When I'm starting a pipeline, I often want to get a notification when it completes or fails. Other users have requested the same thing.
This is the first step in that process. In the UI, we can just include a checkbox if they're authenticated to send an email or text message (if configured).
@spinnaker/netflix-reviewers WDYT?

allow users to send additional notifications when triggering pipelines

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/PipelineServiceSpec.groovy

Shame on me for not writing a test. It turns out that, when calling `addAll` like this, Groovy just appends the argument into the caller, so you have a List with the original items plus the other collection.

fix notification merging

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy

Change to expose the `accountId` field now sent from clouddriver via https://github.com/spinnaker/clouddriver/pull/884

include accountId in /credentials response

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/SnapshotController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/SnapshotService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/Front50Service.groovy

Added functionality to get the current snapshot and the snapshot history from front50. This will be used to surface snapshots that are available for the user in deck. PTAL @lwander @duftler @danielpeach

core: Implemented a controller for getting snapshots from front50

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GitHubProperties.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/github/GithubTeamsUserRolesProvider.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/github/client/GitHubClient.groovy

Noticed that I was getting sporadic results when querying GitHub for Team AuthZ. I noticed that GitHub by default limits to only 30 teams. My organization at the time had 30. GitHub allows you to increase this upwards to 100.
This pull request is to expose the per_page parameter if people need to make it larger than 30. After speaking to some folks, I set a default value 30 (as per GitHub's standard), but allow to increase through the properties.
Link to relevant documentation from GitHub API: https://developer.github.com/v3/#pagination

Exposing GitHub API per_page value to accomodate teams larger than 30

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GitHubProperties.groovy

The previous merge request #272 has caused some issues; namely that we required an int to be `@NotEmpty` which is a typo/bug and we also talked about not making this a mandatory value so removing the annotation all together.

Removed @NotEmpty annotation on paginationValue

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ProjectService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/Front50Service.groovy

- Updated call to front50 project's api to handle both the old & the new return type.
Front50 will use Set<Projects> projects instead of Resources<ProjectResource> project (HAL)

Prepping for Front50 Project API refactor

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy

This PR is broken into two independent commits. The first makes the nested static classes of the ApplicationService consistent, and the second ensures that any exception throwing by the `ExecutorService` is unwrapped and rethrown as the source exception (so that the proper `UpserviceBadRequestException` handler is invoked)
@jtk54 @duftler PTAL

ApplicationService renames + exception handling

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/config/ServiceConfiguration.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/health/DownstreamServicesHealthIndicator.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/HealthCheckableService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/health/DownstreamServicesHealthIndicatorSpec.groovy

- Uses request parameters to determine whether to check downstream services
- Downstream services are checked asynchronously (and only until success occurs)

Optionally check the health of downstream services

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/github/GithubTeamsUserRolesProvider.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/rolesprovider/google/GoogleDirectoryUserRolesProvider.groovy

This allows someone to add the `auth` block to `spinnaker-local.yml` if they so chose, and it will only be picked up by Gate if Fiat is disabled.
@duftler @jtk54 PTAL
/cc: @gbougeard 
Fixes https://github.com/spinnaker/fiat/issues/83

Adds check for Fiat in user roles provider conditional

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509RolesExtractor.groovy

Allows extensions to define strategies of providing roles from X509 certificates.
PTAL @ttomsu @ajordens

Adding interface to pull user roles from X509 certificates

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/EntityTagsController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/EntityTagsService.groovy

Example Queries:
- `/tags?tag:environment=test`
- `/tags?idPrefix=aws:cluster`
- `/tags?cloudProvider=aws`
- `/tags?entityType=iamrole`
- `/tags/aws:cluster:front50-main:mgmt:*`

Expose /tags and /tags/{id}

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/AccountLookupService.groovy
gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/DefaultProviderLookupService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CredentialsService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/FunctionalSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/CredentialsServiceSpec.groovy

The accounts are checked every request to augment authentication details, this saves a round trip call to clouddriver in every request (instead at most every 2 seconds as the entry expires out of the loading cache)
@robzienert PTAL

Use the temporary account cache to supply the account list for credentials service.

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/InsightConfiguration.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/InstanceService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/config/InsightConfigurationSpec.groovy

Allows insight links to be specific to particular providers based on `cloudProvider` field.
depends on https://github.com/spinnaker/clouddriver/pull/1268

filter insight links by provider

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/InstanceService.groovy

We have an unfortunate context issue in Titus which results in `instanceId` getting overwritten in the `context` map by the `id`.

do not override instance details when generating insight link context

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServices.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServicesSpec.groovy

Low-hanging fruit to support regex expressions in oauth2 user info requirements. Requires values to have a `/expr/` format.
Fixes https://github.com/spinnaker/fiat/issues/124
@ttomsu @msloes

Adding regex support for oauth2 user info requirements

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/filters/CorsFilter.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/filters/GateOriginValidator.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/filters/OriginValidator.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/filters/GateOriginValidatorSpec.groovy

*Note:* this is a breaking change for anyone that is currently relying on the cors filter to allow any requesting domain with authentication, and is hitting the spinnaker API directly from other browser based web apps besides deck.
Adds a new `cors.allowedOriginsPattern` configuration property that takes a regex to match against the request origin. If successful, the request origin is returned as the `Access-Control-Allow-Origin` header. If unsuccessful, `*` is returned and the browser will then not supply cookies.
If not configured, then falls back to checking the hosts configured in the `services.deck.redirectHostPattern` property. Finally falls back to matching `services.deck.baseUrl`.
A reasonable example value for `cors.allowedOriginsPattern` would be:
````yaml
cors: …
```

Restrict cross origin requests.

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/health/RedisRelaxedHealthIndicator.groovy

This avoids a scenario where a momentarily blip with Redis (used for auth sessions)
knocks `gate` instances out of an ELB and effectively takes down Spinnaker for both
UI and API users.

A relaxed RedisHealthIndicator that will never report DOWN once UP

---

gate-web/gate-web.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/ldap/LdapSsoConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PermissionService.groovy

Enables ability to specify the user's DN & search for groups. Groups are pushed to Fiat, if enabled.
Would love for someone on the bug to pull this down and try it out. I'm no LDAP expert, so I don't know what real, in-the-field DIT layouts are.
@duftler @jtk54 @cfieber PTAL
cc @scotmoor @rguthriemsft 
tag: https://github.com/spinnaker/fiat/issues/30

Adds initial, basic LDAP support, including groups/roles extraction

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509UserIdentifierExtractor.java

This can be used to decorate additional information into a user's identity for non-human users (e.g. an application X509 in AWS could look like: `{app}-{accountId}-{instanceId}` for example).

Adding X509UserIdentifierExtractor interface

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/EventController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/AuthConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/EventService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/EchoService.groovy

Extracts and forwards the GitHub signature header, if present.
Additionally, POST calls to `/webhooks/**` need to have auth requirements opened up, which is also included in this PR.
@duftler @jtk54 @cfieber @ajordens. 
tag: https://github.com/spinnaker/fiat/issues/134

Passes 'X-Hub-Signature' through on webhook calls

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ExecutionsController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/TaskController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/TaskService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaService.groovy

Not sure if this is the direction we'd like to go - exposing a generic endpoint like this?
```
{
"runningExecutions": {
"i-1234": 9000,
"i-5678": 0,
...
}
}
```
@robfletcher

Adding endpoint to expose Orca task execution status metrics

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ServerGroupService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/ServerGroupServiceSpec.groovy

@anotherchrisberry or @cfieber please review.
It's currently not possible to have provider specific insight actions for server groups, since the context never includes `cloudProvider`. This just follows the pattern used in the instance service.

add full context to server group insight actions

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/BatchEntityTagsController.java

`/batch/tags/batch` is a little redundant

clean up batch endpoint (remove extra batch in path)

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/EventController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/EventService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/EchoService.groovy

PR [#153](https://github.com/spinnaker/igor/pull/153) has been opened against Igor.
PR [#137](https://github.com/spinnaker/echo/pull/137) has been opened against Echo.
A PR is also being opened against Deck.
BitBucket Server (a.k.a. Stash) support already exists. This adds BitBucket Cloud support of pipeline triggers based on BitBucket webhooks and provides Orca the ability to retrieve a list of commits from BitBucket as part of it's GetCommits stage.

Add BitBucket support

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/RateLimiterConfig.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/RateLimiterConfiguration.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/Rate.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimiter.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptor.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RedisRateLimiter.java
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ratelimit/RedisRateLimiterSpec.groovy

I opted for a bucketed approach, rather than a sliding window since it's a lot simpler from a storage perspective. We can avoid horrible, bursty death by making the buckets smaller, which should suffice.
```
rateLimit:
enabled: true
learning: true
redis:
enabled: true
capacity: 5
rateSeconds: 30
capacityByPrincipal:
anonymous: 50
```

Adding basic API rate limiting

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/AuthConfig.groovy

@cfieber @ewiseblatt @gardleopard FYI

Enable Basic Auth in order to support spectator sidecar adaptor

---

build.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/Main.groovy

mitigates a potential DDoS attack of repeatedly renegotiating TLS
picks up latest kork version for TLS config updates
requires release of https://github.com/spinnaker/kork/pull/75 and 
https://github.com/spinnaker/spinnaker-dependencies/issues/77

fix(tls) - disable TLS client renegotiation, update kork

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/SecurityGroupService.groovy

Fixes SPIN-2443  
Passing the vcpId to the getSecurityGroup method. This should result in more consistent results coming back.

Fix inconsistencies when fetching Security Groups by ID

---

gate-web/config/gate.yml
gate-web/gate-web.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CredentialsService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PermissionService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/FunctionalSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/CredentialsServiceSpec.groovy

Gate is the special snowflake of why the `services.fiat.autoConfig` property was added. https://github.com/spinnaker/fiat/pull/154 addressed the problem that `autoConfig` wasn't really supposed to be a user-configurable flag - instead it was more supposed to be a component-specific attribute. 
@cfieber @jtk54 - this is a non-`@EnableFiatAutoConfig` component (the only one). PTAL.
Tests won't pass until https://github.com/spinnaker/fiat/pull/154 is submitted and released.

chore(fiat): Bumps Fiat API, dropping autoConfig property

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CredentialsController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/AuthConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy

`security.basic.enabled`.
@anotherchrisberry - you added the `basicAuth.enabled` in response to a PR I made. There already exists a standard property, which this PR uses instead of that one. It also looks like there is already a `gate.properties` [file](https://github.com/spinnaker/gate/blob/master/gate-web/src/main/resources/gate.properties) that turns this property off by default, but I don't know if you guys deploy with that file (because I don't think you deploy with the internal gate-web/config/gate.yml file).
Please confirm that this change does not pop up that HTTP Basic browser dialog box.
@jtk54 PTAL, too.
@lwander, @ewiseblatt FYI

chore(auth): Removes basicAuth.enabled in favor of standard 

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/InstanceService.groovy

@icfantv or @anotherchrisberry please review.
`instanceDetails` and `accountDetails` shouldn't be merged, since the instance details endpoint returns this merged map. This change still populates the insight action context.

fix(instanceService): prevents merge of instance and account details

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/Rate.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptor.java

Some small improvements to rate limiting:
* Added `X-RateLimit-Learning` bool header. 
* Send rate limit headers in learning mode.
* Intercepting all 429 errors to verify the rate limit headers are added (Hystrix circuit-breaking, for example, wasn't returning rate limit errors). If the reset header is undefined, the date is set to five seconds in the future.
* Consistency between learning/enforcing log messages
@spinnaker/reviewers PTAL

feat(web): Adding rate limit headers to all 429 errors

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptor.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RedisRateLimiter.java
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ratelimit/RedisRateLimiterSpec.groovy

Allows the ratelimiter to bucket anonymous principal usage by their source IP, rather than bucketing all anonymous users into the same bucket. Any `capacityByPrinicipal` settings for `anonymous` will still apply to all anonymous principals.
@robfletcher PTAL

feat(ratelimit): Adding source IP address to anonymous prinicipal

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/RateLimiterConfiguration.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptor.java
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptorSpec.groovy

Adds capability to enforce rate limits for specific principals while in learning mode, as well as enable learning mode for specific principals when in enforcing mode.
@robfletcher PTAL

feat(ratelimit): Add enforcing & ignoring principal list configs

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/ldap/LdapSsoConfig.groovy

Exposes additional spring-security fields for the LDAP configuration that allow resolving the user via search instead of a user DN template.
See [here](https://github.com/spinnaker/fiat/issues/30#issuecomment-289835132) for discussion, and a corresponding fiat PR at https://github.com/spinnaker/fiat/pull/169.

feat(authN/ldap): Adds userSearchBase and userSearchFilter properties for LDAP

---

gate-web/src/main/resources/gate.properties

Spring endpoints (such as /env and /resolvedEnv) are currently overexposed. This PR removes the settings that expose them.
This means that an admin will need to know the HTTP Basic username/password in order to hit those endpoints when some form of authentication is turned on (OAuth, SAML, etc).
@cfieber @jtk54 PTAL
@skim1420 @lwander FYI

fix(auth): (Re)add auth protection for Spring management endpoints

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ApplicationController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ApplicationServiceSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/FunctionalSpec.groovy

This allows cluster details to be turned off when requesting details from the application view as getting a list of clusters can be expensive. i.e, `http://localhost:7002/applications/titustestapp?clusters=false`.

feat(applications): allow clusters to be skipped when application details

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/interceptors/RequestLoggingInterceptor.java

Basic request logging interceptor, which we need to help identify API client behaviors while evaluating rate limit capacities. Since we don't proxy gate with Apache or anything else, it's hard to determine what clients are actually doing when they're being rate limited.

feat(web): Adding request logging interceptor

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineTemplatesController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineTemplateService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/Front50Service.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/PipelineTemplateControllerSpec.groovy

Adds create, update & read endpoints for pipeline templates. I waffled around on how to handle spinnaker-backed templates, and figured explicit publish actions (as opposed to trying to figure out a git-backed solution) would be the easiest path. Requires sending the templates as JSON, rather than YAML.
@spinnaker/netflix-reviewers PTAL initial review

feat(web): Adding pipeline template create/read apis

---

build.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509Config.groovy

when x509 auth is enabled, install a custom SecurityContextRepository that does not persist X509 authenticated contexts
also includes bump of spinnaker dependencies version to latest

disable session creation for x509 authenticated requests

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CredentialsController.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/CredentialsControllerTest.groovy

We have a docker registry account named like `registry.company.domain` and it is resolved as `registry.company`.
Changing the `RequestMapping` parameter to a regex like `.+` solves the issue.

fix(credentials): allow account names with dots

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuth2SsoConfig.groovy

It looks like the ExternalSslAwareEntryPoint component is being created even though the outer class has a ConditionalOnExpression which returns false. I guess as it is a different class found by spring on startup and it doesn't consider it related to the outer class.
So i've simply duplicated the ConditionalOnExpression from the outer class to ExternalSslAwareEntryPoint.
I'm not 100% convinced this is the correct fix - but i thought i'd take a shot at it :)

fix(oauth): Fix UnsatifiedDependencyException

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/RateLimiterConfig.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/RateLimiterConfiguration.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/AbstractRateLimitPrincipalProvider.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitPrincipal.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitPrincipalProvider.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptor.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RedisRateLimitPrincipalProvider.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RedisRateLimiter.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/StaticRateLimitPrincipalProvider.java
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptorSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ratelimit/RedisRateLimitPrincipalProviderSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ratelimit/RedisRateLimiterSpec.groovy

Refactored how configurations are used in the rate limiter so that there's complete parity between static & dynamic configuration values. As part of this work, I also discovered Spring doesn't play nice with email address keys, so I altered the format of the principal overrides.

feat(ratelimit): Parity of static & redis configs

---

gate-web/gate-web.gradle

This bump includes the first cut at read-only permissions as well as disabling FAIL_ON_UNKNOWN_PROPERTIES in the object mapper.
@jtk54 @cfieber FYI

chore(fiat): bump fiat version, fixing deserialization issue

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/WebhookController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/WebhookService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/EchoService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaService.groovy

This adds support for a new endpoint for preconfigured webhooks in Orca.
I was in doubt where to put this logic. I ended up renaming `Event(Service|Controller)` to `Webhook(Service|Controller)` and putting it there, as some other webhook related functionality already lived there. If this is undesired, please let me know, and I'll fix 👍 
Corresponds with https://github.com/spinnaker/orca/pull/1329.

feat(webhooks): Support preconfigured webhook stages

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ApplicationServiceSpec.groovy

As we no longer care about the accounts in Front50 (and we're no longer collecting them), we should not merge them/include them in the application results - instead, we'll rely entirely on cluster data from Clouddriver.

refactor(applications): ignore front50 account entries on applications

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptor.java
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptorSpec.groovy

Seems like this should be fine as far as costs go, despite the high dimensionality.

feat(ratelimit): Adding principal metrics

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ServerGroupService.groovy

We're already doing the same thing for instance insight links, just failed to do it for server group links, which results in `null` values coming back for unmatched links.

fix(insight-links): filter invalid insight links based on cloud provider

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuth2SsoConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServices.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/Front50Service.groovy

This PR takes the concepts of a cloud provider service account, and merges it with a Spinnaker/Fiat service account. By allowing provider service accounts the ability to login, we open up another option for script access (beyond X509 certs)

feat(serviceAccounts): Allows login by registered service accounts

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ApplicationController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/GenericErrorController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/GenericExceptionHandlers.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ProjectController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/SecurityGroupController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ServerGroupController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/V2CanaryController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/exceptions/HasAdditionalAttributes.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/exceptions/NotFoundException.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/StrategyService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/FunctionalSpec.groovy

Introduces a single NotFoundException that can be used in place of all
previous *NotFoundException classes (ie. ApplicationNotFoundException,
SecurityGroupNotFoundException, etc).
The default ErrorController has been replaced with one that will always
return application/json.
A stacktrace will be included if ?trace=true is appended to the request.
Example error response:
```
{
"error": "Not Found",
"exception": "com.netflix.spinnaker.gate.exceptions.NotFoundException",
"message": "Application not found (id: some_application_name)",
"status": 404,
"timestamp": 1499731805410
}
```

feat(web): Generic exception handling

---

.gitignore
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/TaskService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/PipelineControllerSpec.groovy

Moves write operations for pipelines to be orchestrated by orca, rather than being written directly into front50. Keeps the same external payload API as what was previously exposed.
Depends on https://github.com/spinnaker/orca/pull/1442

refactor(web): Pipeline create/update now go through orca tasks

---

.gitignore
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/TaskService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/PipelineControllerSpec.groovy

Reverts the revert of #434.
Change done here is to base64 encode the pipeline so that pipeline expressions are not evaluated.
Depends on https://github.com/spinnaker/orca/pull/1515

feat(web): Save pipelines via orca

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy

Spring automatically treats the last part of a URL path as a file if it includes a known extension, e.g. `.c` or `.pdf`, which breaks searches in those cases.

fix(core): disable favorPathExtension

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/TaskService.groovy

If the save takes longer than 10 seconds right now, we end up throwing a NPE. This adds a few guards against that, as well as some logging to help troubleshoot errors.
@robzienert PTAL

fix(pipelines): add logging, guards in pipeline save code

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/DataController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/DataService.groovy

Results are streamed directly from clouddriver.
```
curl http://localhost:7101/v1/data/static/my_static_id
curl http://localhost:7101/v1/data/adhoc/titus/my_account:us-east-1:my_bucket/TitusWorker-001/stderr
```

feat(web): Expose the /v1/data/[static|adhoc] api from clouddriver

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsService.groovy

allows granting read or write permission to specific certificates

fix(x509): add the cert identity as a role for authz checks

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ApplicationServiceSpec.groovy

Front50 improvements should make this behavior unnecessary. 
@ajordens PTAL

fix(web): reverting pipeline refresh behavior

---

gate-web/gate-web.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/ldap/LdapSsoConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/hystrix/spectator/HystrixSpectatorConfig.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/FunctionalSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/config/RedisTestConfig.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/FormLoginRequestBuilder.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/GateSystemTest.java
gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/YamlFileApplicationContextInitializer.java
gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/ldap/ApacheDSServer.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/ldap/ApacheDSServerSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/ldap/LdapAuthSpec.groovy
gate-web/src/test/resources/ldap-server.ldif
gate-web/src/test/resources/ldap.properties
gate-web/src/test/resources/logback-test.xml
gradle/ldap.gradle

We're sorely lacking proper auth tests, so this PR will hopefully take us a step in the right direction.
The tests stand up an embedded LDAP server (ApacheDS) to authenticate against. An LDIF file is included that defines two users, but only one is used in the tests.

test(LDAP): Adds ldap integration tests

---

build.gradle
gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/commands/AbstractHystrixCommand.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/InsightConfiguration.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ApplicationController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/filters/FiatSessionFilter.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/interceptors/RequestLoggingInterceptor.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptor.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RedisRateLimitPrincipalProvider.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServices.groovy

Enables generation of a X-SPINNAKER-REQUEST-ID per inbound request and sets as a request header on all downstream requests (kork 1.100.0).
Annotation for JSON logging.

feat(web): Enable request trace header, log annotation

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuth2SsoConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuthSsoConfigurer.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509Config.groovy

Changes made along with the Spring Boot version bump in #433 seem to have caused x509 config to be ignored when OAuth is also used.  The certificate would still be required in order to establish a connection but would not be used for authentication and so all requests would be handled as an anonymous user and redirected to the login URL.  This change just mirrors the existing approach for allowing x509 and SAML to coexist.

fix(x509): Allow OAuth and x509 to be used together again

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineConfigController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineTemplatesController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaService.groovy

What I'm kinda thinking is this endpoint could get exposed in deck like so:
Maybe `Export to Pipeline Template` or something? This would just pop-up a modal with a textbox that has the result of that endpoint.

feat(pipeline_template): Convert pipeline config to pipeline template

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/AuthController.groovy

Was working with @ndouglascampbell on a Gate/Deck redirect issue, and we found this bug. We have the following variables set in our configuration files.
**gate.yml:**
```
services:
deck:
baseUrl: https://spinnaker.foo.com:443
```
**URL Post AuthN**
`https://gate-url:8084/auth/redirect?to=https%3A%2F%2Fspinnaker.foo.com%2F%23%2Finfrastructure`
This caused an the conditional in this MR to fail due to the ports; when it tried to compare the address in the configuration vs the redirect address in the query param. 
For the deck `baseUrl`, it got a port value of `443`. (Redundant, we know, but we were migration from a config where we listened to SSL on a different port). For the query param in the url, it got a value of `-1` (the default value if no port specified).
If port 443 is missing, but …

fix(authN): Handle case of missing port(s) in post authN redirect

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServices.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/provider/GithubProviderTokenServices.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/provider/SpinnakerProviderTokenServices.groovy

This adds the ability to restrict github authentication to only users belonging to a certain organization. It adds in a provider specific beanto encapsulate the parts that aren't general oauth2 handling. The interface is defined in SpinnakerProviderTokenServices, and it's just a single call that takes the user token and the map of user info. The github provider bean keys off the
security.oauth.providerRequirements.type setting being 'github', and if so it loads the extra provider specific requirements.  This is a proposed fix for spinnaker/fiat#188
We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).
When filling out a pull request, please consider the following:
* Follow the commit message conventions …

feat(authN): Restrict github auth by organization membership

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CredentialsService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/CredentialsServiceSpec.groovy

As part of migrating to fiat enabled, I want to support the production migration from requiredGroupMemberships based configuration in clouddriver to permissions based configuration - this change will support both but prefer the non-deprecated format

feat(authz): support migrating clouddriver account authz config to permissions

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/SearchController.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/SearchControllerSpec.groovy

Otherwise it's likely the search will timeout after 60s for larger
environments.

fix(search): Ensure that keyword searches are >= 3 characters

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/AccountLookupService.groovy
gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/DefaultProviderLookupService.groovy
gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CredentialsController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CredentialsService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/InstanceService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/CredentialsControllerSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/ldap/LdapAuthSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/CredentialsServiceSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/InstanceServiceSpec.groovy

This was a lot more work than I thought.
Companion PR to expose the `?expand` flag for Clouddriver's `/credentials` endpoint (https://github.com/spinnaker/clouddriver/pull/2326)
I made the details somewhat more strongly typed, but not convinced this buys us more than a regular `Map`.

feat(credentials): provide proxy for ?expand on /credentials

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy

app engine returns a list of string for the regions field.

fix(credentials): collection<map> isnt compatible with app engine regions response

---

gate-web/etc/init/gate.conf

Changing to appending to the log file so logs will correctly rotate.  This prevents large amounts of null data at the start of a rotated log file.

fix(gate/log): Append to log instead of overwrite

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/DefaultProviderLookupService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CredentialsController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CredentialsService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/CredentialsControllerSpec.groovy

When listing credentials without fiat enabled, return all credentials.
Adds an 'authorized' flag to indicate whether the account is suitable
for deployment.
This allows properly filtering UI dropdowns but preserving account
metadata since unauthorized resources are still rendered in the UI

feat(authz): include full credentials list

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/SearchController.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/SearchControllerSpec.groovy

The search endpoint rejects short queries, returning an empty
result set.  There are a few cases where we need to pass a short
query; create an explicit flag to make this possible.

fix(provider/gce): Allow short queries with explicit flag

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/DefaultProviderLookupService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/SchedulingConfigurerConfiguration.java

Given that accounts rarely change, it is reasonable to cache the
entire set of accounts from clouddriver for ~30s and refresh on a
background thread.
This handles a situation where `clouddriver` is momentarily unavailable.

fix(credentials): Swap `LoadingCache` for `@Scheduled`

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CredentialsService.groovy

There is no longer a remote call in the direct call path of
`CredentialsService.getAccounts()`, thus no need for hystrix.
The `CredentialsService` was originally getting called for every x.509
authentication request. The default hystrix configuration had placed
an artificial limit on the number of concurrent api requests that could
be served by `gate`.

fix(credentials): Remove hystrix from `CredentialsService`

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ApplicationController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ArtifactController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/AuthController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/BuildController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ClusterController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ImageController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/JobController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/LoadBalancerController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/NetworkController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ProjectController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/SearchController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ServerGroupManagerController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/SnapshotController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/SubnetController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/TaskController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/aws/AmazonInfrastructureController.groovy

Also expands the existing `ApiOperation` definitions to include response types and containers (e.g. "List"). This is going to be helpful for our API docs as well as helping to generate API client libs via `swagger-codegen` in the future. @imosquera FYI.

chore(api): Finish swagger annotations.

---

build.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy

Also a change to our web configuration. The upgraded spring version that comes with this spinnaker-dependencies bump added more validation (https://github.com/spring-projects/spring-security/issues/4995) and is wired up correctly when using more of the auto configuration features of Spring that we don't use. I'm not eager to start using more auto config, so this just adds the missing bean.

chore(core): Upgrade spinnaker-dependencies to 1.152.1

---

gate-web/gate-web.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/iap/IAPAuthenticationFilter.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/iap/IAPConfig.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/Front50Service.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/iap/IAPAuthenticationFilterSpec.groovy

Cloud Identity-Aware Proxy provides authentication for GCP backend services via Google OAuth2.0 and IAM policies. It also adds JSON Web Tokens in the incoming request headers for securing the application. This PR adds a new security module to validate the request using the token and authenticate the user, via a `PreAuthenticatedAuthenticationToken` and the user email from the payload. It handles the sign-in to Fiat, and caches the token signature in the session so that subsequent requests with same signature can skip validation.
https://cloud.google.com/iap/docs/signed-headers-howto#verify_the_id_token_header
Example configuration:
```
security:
iap:
enabled: true
audience: /projects/{project_number}/backendServices/{service_id}
```

feat(cloud-iap): Add new security config to integrate with Cloud IAP.

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/config/Service.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ExecutionsController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineConfigController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/interceptors/RequestContextInterceptor.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/RequestContext.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ExecutionHistoryService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineTemplateService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ProjectService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/SecurityGroupService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/TaskService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/WebhookService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaServiceSelector.java
gate-web/src/test/groovy/com/netflix/spinnaker/gate/FunctionalSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/PipelineServiceSpec.groovy

Applies `ServiceSelector` from kork to gate's `OrcaService`, enabling routing requests across multiple orca clusters by any [supported selector class](https://github.com/spinnaker/kork/tree/master/kork-web/src/main/java/com/netflix/spinnaker/kork/web/selector). This implementation targets sharding orca's queue (such as by varying `keiko.queue.redis.queueName` per orca cluster) in order to partition compute resources by i.e. spinnaker application or request origin, but assumes a common execution repository across all orca clusters.
Example configuration:
```
services:
orca:
shards:
baseUrls:
- baseUrl: https://localhost:8083
- baseUrl: https://localhost:9083
priority: 10
config:
selectorClass: com.netflix.spinnaker.kork.web.selector.ByApplicationServiceSelector
applicationPattern: spintest …
```

feat(core): ServiceSelector orca queue sharding

---

gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/ldap/LdapAuthSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/swagger/GenerateSwagger.groovy
swagger/generate_swagger.sh
swagger/swagger.json

@danielpeach FYI this is an easier way to get the spec for the API docs as well. We'll have to use this in our TravisCI builds to ensure changes to the API don't break the swagger spec (and anything depending on it).

chore(swagger): Adds a gradle task and script to generate swagger spec.

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy

expressions require much urlencoding, this adds POST handling for text/plain or JSON object
for slightly easier adhoc cli usage

feat(expression): evaluateExpression supports POST

---

build.gradle
gate-proxy/gate-proxy.gradle
gate-proxy/src/main/kotlin/com/netflix/spinnaker/config/ProxyConfiguration.kt
gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/ProxyController.kt
gate-web/gate-web.gradle
gradle/kotlin.gradle

This PR allows for selective proxying of requests through `gate`.
It is particularly useful when a UI component wants to communicate with
a service that does not offer up permissive CORS headers.
Still a few outstanding bits to implement:
- success/failure metrics
- method restriction (config supports it, implementation does not)
Example Config:
```
proxies:
- id: spinnaker-readonly
uri: http://spinnaker.com
methods:
- GET
- POST
```
Example Usage:
```
curl localhost:7101/proxies/spinnaker-readonly/health
{
"status": "UP"
}
X-Proxy-Status-Code: 200
X-Proxy-Url: http://spinnaker.com/health
Content-Type: application/vnd.spring-boot.actuator.v1+json;charset=UTF-8
```

feat(web): Support for proxying generic URLs through `gate`

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/OidcClientConfig.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/OidcConfigController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/NoopOidcConfigService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/OidcConfigService.java

OIDC Configs will be very install specific so this just adds the interface and a `NoopOidcConfigService` that returns an empty list. The assumption is that custom installs will wire up their own OIDC Config providers.

feat(loadBalancers): Add support for an oidc config endpoint

---

.gitignore
gate-core/gate-core.gradle
gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/DefaultProviderLookupService.groovy
gate-core/src/test/groovy/com/netflix/spinnaker/gate/services/DefaultProviderLookupServiceSpec.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CredentialsService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/CredentialsServiceSpec.groovy

Moves the translation of / preference of permissions over requiredGroupMemberships to the
DefaultProviderLookupService which refreshes on a 30s interval rather than every time
permissions are evaluated in CredentialsService.

fix(logging): reduce legacy permission logging

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CredentialsController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/AllowedAccountsSupport.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/anonymous/AnonymousConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/ldap/LdapSsoConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServices.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PermissionService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/CredentialsControllerSpec.groovy

Continue to propagate X-SPINNAKER-ACCOUNTS header when
fiat is enabled, allowing a live upgrade into fiat.
Removes auth filtering on /credentials endpoint.
Credentials include an authorized flag which can be used
for filtering choices in the UI, but account metadata is
required for proper UI rendering even for accounts that
the user does not currently have permission for.
requires spinnaker/fiat#231 for invalidatePermissions

fix(fiat): Transitional support for fiat migration.

---

gate-web/src/main/groovy/com/netflix/spinnaker/hystrix/spectator/HystrixSpectatorPublisherCommand.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/hystrix/spectator/HystrixSpectatorPublisherThreadPool.groovy

I'm not sure this particular metric has any use but it appears that the
recent spectator bump has resulted in it being `NaN`.

fix(hystrix): Avoid an `NaN` when publishing `hystrix.currentTime`

---

build.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/filters/FiatSessionFilter.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/AllowedAccountsSupport.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/AuthConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/anonymous/AnonymousConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CredentialsService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PermissionService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/FunctionalSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/CredentialsControllerSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/anonymous/AnonymousConfigSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/CredentialsServiceSpec.groovy

This allows for fiat to be selectively enabled at runtime via the
`DynamicConfigService` (environment-specific).
The `AllowedAccountsSupport` bean now supports a legacy lookup of
allowed accounts in the event that it's not possible to fetch permissions
from fiat (`legacyFallback` must be enabled).

feat(fiat): Delegate whether fiat is enabled to `FiatStatus`

---

build.gradle
gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/commands/AbstractHystrixCommand.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/AllowedAccountsSupport.java

- Avoid a potential NPE in `AllowedAccountsSupport` if permissions
cannot be loaded.
- Consistently log when a hystrix exception is raised (only `RetrofitError`
was logged previously)

chore(dependencies): spinnaker-dependencies 0.161.3

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PermissionService.groovy

Introduce an ability to override the `services.enabled` check that
`GateConfig.createClient()` is doing.
The check will be left in for historical reasons but it is confusing to
have a null service class injected.

fix(fiat): Always create `FiatService` regardless of `services.fiat.enabled`

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/RetrofitConfig.groovy

Metrics for all okhttp connections will be emitted under
`okhttp.requests`.
Also fix creation of the `ClouddriverServiceSelector` bean that was
broken in spinnaker/gate#565

fix(web): Enable the `OkHttpMetricsInterceptor`

---

README.md
build.gradle

Starting gate with ./gradlew -DDEBUG=true now causes the JVM to listen on port 8184 for a remote debugger.

chore(build): Add debug flag to gate build

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/filters/FiatSessionFilter.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy

Also tweaked the `FiatSessionFilter` to only attempt a permission lookup
(and subsequent HttpSession invalidation) if the `user` is non-null.

fix(fiat): Smidge of logs when loading a saml user

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsServiceSpec.groovy

Since x509 auth doesn't establish a session, every API call results in a login call to fiat.
Given that certificates are unlikely to change on a high frequency this introduces a configuration
option (off by default) to introduce a per instance debounce of login calls for a particular identity
(only call login once every debounceWindow).

feat(x509): debounce login calls to fiat with x509

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CleanupController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CleanupService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/SwabbieService.java

Expose the opt out endpoint for a resource through gate. 
Keep swabbie as a non-required service.
To use, add in `gate.yml`
```
swabbie:
enabled: true
baseUrl: https://localhost:8088
```

feat(swabbie): expose optOut endpoint

---

gate-web/config/gate.yml

The `swagger.json` generated by `swagger/generate_swagger.sh` omits the `pipeline-config-controller` endpoints.  Therefore clients generated from that `swagger.json` file fail to generate methods needed to interact with the `pipeline-config-controller`.  This change adds a search pattern that includes the needed endpoints.

fix(swagger): Include pipeline-config-controller in Swagger

---

gate-web/config/gate.yml

".*pipelines.*" doesn't match "pipelineTemplates", so the pipeline templates API calls were not included in Swagger.
Remove the "s" in ".*pipelines.*" to fix this.

fix(swagger): Include pipeline templates in Swagger

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/filters/CorsFilter.groovy

Gate needs to allow this in CORS before deck can start sending it.

feat(cors): Allow new 'X-Spinnaker-Priority' header

---

gate-core/gate-core.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/interceptors/RequestSheddingInterceptor.java
gate-web/src/test/groovy/com/netflix/spinnaker/gate/interceptors/RequestSheddingInterceptorSpec.groovy

A dumb, coarse-grained request shedding interceptor. For when we need to pull the plug on a part of the system to save the rest of it.
```yaml
requestShedding:
enabled: true
paths: "/projects/.*/clusters,/somethingElse"
chance: 60
```
And then sending a request to gate with `X-Spinnaker-Priority: low`:
```json
{
"error": "Service Unavailable",
"exception": "com.netflix.spinnaker.gate.interceptors.RequestSheddingInterceptor$LowPriorityRequestRejected",
"message": "Low priority requests are not currently being accepted",
"status": 503,
"timestamp": 1536537123528
}
```
Verified that `/health` and `/error` are not intercepted, regardless of header value.
I elected to go with a global chance config instead of per-path to keep the complexity down, since we'll only be using this when things are …

feat(web): Low priority request shedding interceptor

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/iap/IAPSsoConfig.java

fix(iap/x509): Properly call the x509 configurer if set. (#604)

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/EchoService.groovy

This change adds a new endpoint to trigger a pipeline that will send the request through Echo rather than directly to Orca.  By sending the request through Echo, processing steps that happen for automated triggers will also be applied to manual triggers. Eventually we'll migrate existing workflows to go through Echo, but for a safe rollout we're leaving the existing endpoint unchanged.

refactor(core): Create new endpoint to manually trigger with Echo

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/interceptors/RequestSheddingInterceptor.java

`deck` isn't currently propagating this header.

feat(web): Disregard `X-Spinnaker-Priority` when shedding requests

---

build.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/RetrofitConfig.groovy

The connection pool, retry settings and metrics interceptor should be
handled directly in okHttpClientConfig and not needed explicitly in gate.

chore(okhttp): pick up okhttp from spinnaker-dependencies 1.0.26

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/interceptors/RequestSheddingInterceptor.java
gate-web/src/test/groovy/com/netflix/spinnaker/gate/interceptors/RequestSheddingInterceptorSpec.groovy

Ha-ha. Tests for `RequestSheddingInterceptor` could fail sometimes because of the executor service re-running the compilation of paths while executing tests. This causes the spec to transiently fail.

fix(test): Ensure executor service does not run in tests

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/V2CanaryController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/V2CanaryService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KayentaService.groovy

We need this endpoint exposed to the UI to support manual execution of analysis tasks. 
This is my first PR for any of our services, so I'm assuming I've done at least a few things wrong 😆

feat(canary-v2): add ad-hoc/manual execution endpoint

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/RateLimiterConfiguration.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitPrincipalProvider.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptor.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RedisRateLimitPrincipalProvider.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/StaticRateLimitPrincipalProvider.java
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptorSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ratelimit/RedisRateLimitPrincipalProviderSpec.groovy

feat(web): Support rate limits per source application
```
rateLimit:
learning: false
enabled: true
rateSeconds: 10
capacity: 500
redis:
enabled: true
capacityBySourceApp:
- sourceApp: deck
override: 100
```
Source application limits must be explicitly enabled in redis:
```
sadd "rateLimit:enforcing" "app:deck"
```
They can also be overridden in redis:
```
set "rateLimit:capacity:app:deck" 25
```
A per-principal capacity will override that of the source application.

feat(web): Support rate limits per source application

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ApplicationController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/Front50Service.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ApplicationServiceSpec.groovy

A revised take on spinnaker/gate#603 that applies a `@PostFilter`
authorization check.
Depends on spinnaker/front50#375

feat(web): Serve `/applications` out of the recent cache

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CleanupController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CleanupService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/SwabbieService.java

Adding an html response for opt out.
Adding an endpoint for getting a resource.
Adding the framework for a restore endpoint, but holding off on exposing it until aws gives us soft delete. If that won't happen, I'll remove the endpoint.

feat(swabbie): html endpoints for optOut and restore

---

gate-security/src/main/groovy/com/netflix/spinnaker/gate/security/MultiAuthConfigurer.java
gate-security/src/main/groovy/com/netflix/spinnaker/gate/security/SuppportsMultiAuth.java
gate-security/src/main/groovy/com/netflix/spinnaker/gate/security/iap/IAPSsoConfig.java
gate-security/src/main/groovy/com/netflix/spinnaker/gate/security/ldap/LdapSsoConfig.groovy
gate-security/src/main/groovy/com/netflix/spinnaker/gate/security/ldap/LdapSsoConfigurer.groovy
gate-security/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuth2SsoConfig.groovy
gate-security/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuthSsoConfigurer.groovy
gate-security/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
gate-security/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509Config.groovy

This avoids having the X509 provider depend on all the other ones. Simplifies the refactor of each auth provider into its own package.
Part of spinnaker/spinnaker#3498

refactor(auth): Move multi-auth support to a common interface

---

gate-iap/src/main/java/com/netflix/spinnaker/gate/security/iap/IAPAuthenticationFilter.java
gate-iap/src/main/java/com/netflix/spinnaker/gate/security/iap/IAPSsoConfig.java

This fix allows the http basic auth flow to work. You can configure the basic auth in the gate config:
```
security:
basic:
enabled: true
user:
name: stew
password: chen
```

fix(iap/basicauth): Configure the BasicAuth auth manager for IAP.

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CleanupController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/CleanupService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/SwabbieService.java

Exposing lists of marked and deleted resources through gate.
Each list is of the form 
```json
[{
"name": "thename",
"namespace": "aws:account:region:image",
"resourceId": "ami-000"
}]
```

feat(clean): expose list of marked and deleted

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/commands/HystrixFactory.groovy

The HystrixFactory newListCommand function returns an unqualified ListCommand instead of a typed ListCommand<T>, which is causing downstream unchecked cast exceptions.

fix(core): Add type parameter to ListCommand

---

gate-web/config/gate.yml

**Problem**
When enabling file based authz and having Azure as OAuth provider enabled, this [line of code](https://github.com/spinnaker/gate/blob/master/gate-oauth2/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServices.groovy#L99) tries to use the unset variable `username`. This results in a 500 from Spin Deck and the following log entry in Spin Gate `java.lang.IllegalArgumentException: Path parameter "userId" value must not be null`.
There are others having the same issue: https://github.com/spinnaker/spinnaker/issues/2565
**Temporary fix** 
To fix the issue the following gate-local.yml has to be provided.
```
security:
oauth2:
userInfoMapping:
username: userPrincipalName
```
**Proposed solution**
Fix default mapping rules, as suggested by this PR.

Added username mapping to Azure OAuth config

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/WebhookController.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/WebhookControllerSpec.groovy

These changes make Bitbucket Server ping posts no longer fail.

fix(web): Make Bitbucket Server Ping work

---

build.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy

This change provides the option to remove the use of a Spinnaker key store for https communication with Kayenta.  It's controlled by a config setting, and must be explicitly enabled.  The default behavior is to use the standard configured keystore for Kayenta, just like all other internal Spinnaker services over https.

Don't require Spinnaker credentials for Kayenta over https

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/PermissionService.groovy

Retrofit does not support empty body requests.
This is a small change just to make syncs called from gate to work.
```
2018-11-16 13:22:13.300 ERROR 1765 --- [.0-8084-exec-12] c.n.s.g.s.c.AbstractHystrixCommand       : Downstream exception encountered (group: 'permission', command: 'sync')
retrofit.RetrofitError: method POST must have a request body.
at retrofit.RetrofitError.unexpectedError(RetrofitError.java:44) ~[retrofit-1.9.0.jar:na]
at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:400) ~[retrofit-1.9.0.jar:na]
at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[retrofit-1.9.0.jar:na]
at com.sun.proxy.$Proxy98.sync(Unknown Source) ~[na:na]
at com.netflix.spinnaker.fiat.shared.FiatService$sync$0.call(Unknown Source) ~[na:na]
at …
```

fix(fiat/roles/sync): Fix exception in roles/sync

---

halconfig/gate.yml

adds a `server` configuration for proxies by default. this is useful in
cases where you're terminating SSL at an external load balancer. without
this, Gate redirects you to HTTP even though incoming traffic is HTTPS.

feat(halconfig): adds server config for proxies

---

halconfig/gate.yml

Reverts spinnaker/gate#700
This causes an issue with halyard where the `server` block is already being defined. Sample `gate.yml`
```
spectator:
applicationName: ${spring.application.name}
webEndpoint:
enabled: true
server:
ssl:
enabled: false
port: '8084'
address: 0.0.0.0
security:
basic:
enabled: true
user: {}
cors: {}
google: {}
redis:
connection: ${services.redis.baseUrl:redis://localhost:6379}
server:
tomcat:
protocolHeader: X-Forwarded-Proto
remoteIpHeader: X-Forwarded-For
internalProxies: .*
httpsServerPort: X-Forwarded-Port
```

Revert "feat(halconfig): adds server config for proxies"

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ReorderPipelinesController.java

Previously, Deck made one request per pipeline to be re-indexed after re-ordering or deleting a pipeline, which could flood the Tasks panel when an application contained many pipelines. This change exposes endpoints for re-ordering pipeline and strategy configs.
Corresponding PRs:
Deck: [spinnaker/deck#6519](https://github.com/spinnaker/deck/pull/6519)
Orca: [spinnaker/orca#2663](https://github.com/spinnaker/orca/pull/2663)
Front50: https://github.com/spinnaker/front50/pull/448

feat(web): expose `/reorder` endpoints for pipelines and strategies

---

gate-saml/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy

The role delimiter is hard-coded to use semi-colon. This change allows operators to override the delimiter expected by Spinnaker for parsing the SAML assertion.

fix(authn/saml): Make role delimiter configurable

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/Front50Service.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/DeliveryController.java

Reading delivery configs from front50. Exposing as `Map`s for now, because we are not sure about the typing. Upsert/delete is done through an orca task. Auth _should_ be controlled on the front50 end with fiat.

feat(delivery): get all deliverys and single delivery config

---

gate-saml/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy

Fixes https://github.com/spinnaker/spinnaker/issues/4106
The username extracted contains extra [].
`attributes` map contains a `List<String>` as values.  To extract the value correctly, get the first item from the list instead of return the `List`.

fix(authn/saml): Fix extra [] in username

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ConcourseController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/IgorService.groovy

These endpoints help fill out selection boxes for the various parts of the Concourse trigger definition:

feat(triggers): Add autocompletion APIs for Concourse trigger

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ArtifactoryController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ConcourseController.java

Motivation: Gate fails to start if Igor is not enabled. This may impact many users since Igor is not enabled by default in Gate. 
This PR removes Igor as a requirement.

fix(igor): Remove igor as a requirement for artifactory and concourse

---

gate-oauth2/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuth2SsoConfig.groovy
gate-oauth2/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServices.groovy

Change to make SpinnakerUserInfoTokenServices role handling extensible. Our use case is for OpenID Connect that can provide additional information without hitting the userInfoUri - although the change doesn't assume that.
This is related (and complimentary?) to the work done in #688.

feat(oauth2): Allow implementation to provide roles from OAuth2 

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/GoogleCloudBuildController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/IgorService.groovy

As noted on spinnaker/igor#412, making this a separate endpoint from the '/masters' endpoint given that GCB is different enough from other build services to not implement the same interface.

feat(gcb): Add endpoint for listing GCB accounts

---

halconfig/gate.yml

Set integrations.gremlin.enabled from the Halyard feature named --gremlin.
This will work once spinnaker/halyard#1261 is merged.

feat(gremlin): Add Halyard config for Gremlin

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ArtifactController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ArtifactService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/IgorService.groovy

This endpoint will be used for the manual trigger dropdown for artifact triggers to populate the list of available versions.

feat(artifact): expose endpoint for manual artifact triggers

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/PermissionService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/AuthController.groovy

When frequently invoked, this endpoint has the potential to DoS `fiat`.

feat(auth): Restrict `/auth/roles/sync` to Spinnaker administrators

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ArtifactService.java

Allows gate to start up with `services.igor.enabled` set to false.

fix(artifacts): Make igor service optional

---

gate-web/src/test/groovy/com/netflix/spinnaker/gate/MainSpec.java
gate-web/src/test/resources/gate-test.yml

Starts up fiat with only the `baseUrl` for required services.
Similar to https://github.com/spinnaker/orca/pull/2685

test(core): Basic startup test

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/PostConnectionConfiguringJedisConnectionFactory.java

By default, if Spring Boot is configured with Redis sesssions, it will
try to set a system-level property on Redis at startup. If Redis isn't
available, the application will fail to start. Instead, we set that
property the first time we get a connection from the pool.
This also removes the bound JedisPool to make sure all connections come
from the same JedisConnectionFactory (which has its own built-in
connection pooling).

fix(gate) Allow startup before Redis is available.

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/JobController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/JobService.groovy

* **fix(jobcontroller):** getJobDetails must use a POST not a GET to clouddriver
Currenty, calls to /applications/{app}/jobs/{account}/{region}/{name} (in `gate`) will fail
with an error from `clouddriver` that method is not supported because `gate` uses `GET` but
`POST` is expected on the `clouddriver` [side](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/JobController.groovy#L44)
* **fix(jobcontroller):** remove un-used, non-existent API
``/applications/{appName}/jobs` API is not used (as best as I can tell)
And even if it were used, it would fail because it calls to a non-existent
`clouddriver` API

fix(jobcontroller): correct API calls to clouddriver and remove invalid EP

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy

Apparently if an @AutoWired parameter has no @Qualifier, it will accept
both unqualified AND qualified beans. I assumed it worked like Guice,
which only matches unqualified beans with unqualified parameters.
Whoops.

fix(gate): fix startup with redis.configuration.secure

---

halconfig/gate.yml

Related Halyard PR: https://github.com/spinnaker/halyard/pull/1293
I previously had the wrong idea about how Halyard was propagating config. This should put all of the burden onto Halyard to do it programatically.

fix(gremlin): Remove Gremlin config template and let Halyard write it from scratch

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/Main.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/FunctionalSpec.groovy

We can reenable it once we upgrade to a version of spring-boot with the
fix for spring-projects/spring-ldap#473

fix(ldap): Disable the broken LdapHealthIndicatorAutoConfiguration

---

gate-saml/gate-saml.gradle
gate-saml/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy

Fixes an issue where the session cookie was being marked SameSite by the boot2 upgrade
and as a result we would lose an existing session / start a new session after redirect
back from the IdP.
No longer requires EmptyStorageFactory (went in as a workaround for this issue initially),
and fixes redirect after login back to the original request URI being busted.

fix(saml): ensure session cookie survives idp redirect

---

gate-oauth2/gate-oauth2.gradle
gate-oauth2/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuth2SsoConfig.groovy

Similar to #801 when using oauth removes the samesite attribute from
the session cookie.
I don't 100% know this is necessary but [this post](http://blog.64p.org/entry/2018/11/09/180956) sort of implies it is and a [user report of redirect URI issues that may be related](https://github.com/spinnaker/gate/commit/271bfab61d1f44d8ff7d4f546ec2a8efbb9b1a47#commitcomment-33558040)

fix(oauth): remove samesite cookie attribute

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/EntityTagsController.java

The clouddriver [entityTagsController](https://github.com/spinnaker/clouddriver/blob/d15d7f775c30056510aca016c712e1d68c16d51a/clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/EntityTagsController.java#L53) has all these options that we don't expose when we expose entity tagging through gate. Adding an api that exposes these also so it's easy to grab a subset of entity tags.

fix(tags): expose params for better searching

---

build.gradle

according to [gradle docs](https://docs.gradle.org/5.3.1/userguide/java_plugin.html#sec:java_plugin_and_dependency_management)
`runtime` is a deprecated scope and we should be using `runtimeOnly`

chore(core): replace runtime with runtimeOnly in build.gradle

---

gate-saml/gate-saml.gradle

Adds some explicit references to transitive dependencies that were
causing a groovy compiler error on the gate-saml module

chore(dependencies): fix for intellij groovy compiler

---

gate-ldap/src/main/groovy/com/netflix/spinnaker/gate/security/ldap/LdapSsoConfig.groovy
gate-web/gate-web.gradle
gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/ldap/LdapAuthSpec.groovy

Allows but does not require http basic authentication credentials.
If not present or invalid, will redirect to the login form, but
this will allow API callers to supply credentials via an
Authentication HTTP header.

fix(ldap): allow http basic credentials for LDAP auth

---

gate-oauth2/gate-oauth2.gradle
gate-oauth2/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServices.groovy
gate-oauth2/src/test/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServicesSpec.groovy

Similar to the SAML implementation, adds retries on calls to fiat, and if legacyFallback
is enabled makes a failure to login to fiat non-fatal.

 feat(oauth): add retry/legacyFallback support 

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ArtifactController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ArtifactService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/IgorService.groovy

Adding this optional parameter so that artifact providers can have more information on what artifacts to return.
For example, you could specify 
`provider/my-artifact?releaseStatus=snapshot` to get only candidate artifacts.

feat(artifacts): add optional release status param to fetching artifacts

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ApplicationServiceSpec.groovy

Addresses an issue where the attributes of `cachedApplication` were
overriding the most recent values from `front50`.

fix(web): Better merging of `/applications/{app}?expand=false` responses

---

gate-web/gate-web.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/yaml/YamlHttpMessageConverter.java
gradle.properties

Gate needs to accept yaml, because we want to support both json and yaml in keel.

feat(keel): add yaml processing

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/converters/JsonHttpMessageConverter.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/converters/YamlHttpMessageConverter.java

For some reason if you specify a yaml converter and not a json one (or, before a json one) then the default response is yaml. This PR fixes that unfortunate weird behavior.

fix(json): json is returned as the default for controllers

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/interceptors/RequestLoggingInterceptor.java

This will make it easier to track down particular client libraries
when multiple connectors are being used.

feat(web): Include `requestUserAgent` and `requestPort` in request log

---

build.gradle
gate-bom/gate-bom.gradle

compileOnly dependency should not be added to generated pom.xml,
see discussion: https://discuss.gradle.org/t/publishing-plugin-should-respect-compileonly-configuration/22903/2
see related commit: nebula-plugins/nebula-publishing-plugin@a5432aa

fix(bom): Fix generated pom.xml to omit invalid lombok declaration

---

gate-saml/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy

The default  maxAuthenticationAge is 7200 in upstream spring module.  
This change allows configuring the maxAuthenticationAge as per any other SAMLSecurityConfigProperties entry.
Example gate-local.yaml:
```
saml:
maxAuthenticationAge: 604800
```
This made by possible by the following stale PR, and replaces it:
https://github.com/spinnaker/gate/pull/550

fix(saml): Allow overriding maxAuthenticationAge

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingInterceptor.java

registry.gauge() actually tells the registry to regularly poll the value
of the passed number, which is clearly not the intent.
Replaces the (broken) rateLimit.principal.remaining gauge with a
rateLimit.principal.requests counter tagged by principal, which
should be more helpful in debugging rate limiting complaints.

fix(ratelimit): replace broken use of gauge with a counter

---

gate-oauth2/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuth2SsoConfig.groovy

See https://github.com/spinnaker/gate/pull/826

fix(oauth2): Add before filter to fix basic auth

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaService.groovy

Orca no longer supports the /pipelines/<id>/logs endpoint, so this
proxy in gate _always_ returns 404, confusingly saying "Pipeline not
found".
Ref.
https://github.com/spinnaker/orca/commit/cb9d5da853c304635d83e7777b38b48d5b774c05

chore(cleanup): Remove no-longer-supported API

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java

Wiring up the endpoints in keel related to 'veto' plugins (https://github.com/spinnaker/keel/pull/348) so we can start letting folks opt out of keel management in the UI.

feat(keel): add veto-related endpoints

---

gate-saml/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy

Fixes: https://github.com/spinnaker/spinnaker/issues/4924 by making email address lookup from the SAML assertion configurable for when SAML is configured to NOT use email as the subject nameId.

fix(authn/saml): Make saml email address configurable

---

gate-web/src/test/groovy/com/netflix/spinnaker/gate/swagger/GenerateSwaggerSpec.groovy

Spin cli relies on the swagger.json file generated from this to create the gate client api. Without the canary config store set to true, the swagger.json omits the api endpoints defined in the [CanaryConfigController](https://github.com/spinnaker/gate/blob/master/gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/V2CanaryConfigController.groovy#L32). This is because of the conditional bean on the CanaryConfigService.

fix(swagger): Enable canary config store for generating with swagger

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java

I _think_ we can do this for all the controllers in gate. Right now gate just sends the status code to the caller and swallows any helpful message from a downstream service. This PR passes the status code and message through to the caller. If applied to every controller in gate this might expose some bad error messages, or too much information, but I think it would be better than what we have now. Thoughts on (in a separate PR) applying this broadly through gate @robzienert?

fix(keel): passthrough errors

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/BakeService.groovy

Adding a display name field to base image properties, for cases when the bakery expects specific value and we want to have a custom name.

feat(displayNameBaseOs): Add displayName to baseOS

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ArtifactController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ArtifactService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/IgorService.groovy

This endpoint exists in igor, but wasn't exposed through the UI. It's not currently needed for anything but it's really helpful when debugging things like "can we actually fetch this artifact" or "what does an artifact look like".

feat(artifact): expose get single artifact

---

.idea/README.md
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/V2CanaryController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/V2CanaryService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KayentaService.groovy

Exposes Kayenta's API for running a canary execution given a supplied canary config. This is to enable dry-running canary configs via retrospective from spin CLI. This shortens the development loop when creating/updating canary configs.

feat(canary): Exposes API initiating canary given a config.

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java

Exposing the ad-hoc diff endpoints through gate. They're exposed as a map right now, until we decide that this format is okay. Then I'll create a real object in kork.
Implemented in keel in https://github.com/spinnaker/keel/pull/512 and https://github.com/spinnaker/keel/pull/513.

feat(keel): add diff endpoints

---

gate-saml/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy

Both the SAML metadata and keystore files need to be prefixed with "file:". This simply adds that prefix if it isn't already there.
@cfieber this would help clean up the logic around secret file decryption in the services (along with kork PR: https://github.com/spinnaker/kork/pull/388)

feat(saml): add prefix to saml files if not present

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java

Spring + Swagger is, as usual, totally impossible to predict. There are two different ways of annotating query parameters (`@Query` and `@RequestParam`) and while I cannot for the life of me tell the difference between the two or why they exist, it appears the Swagger UI supports `RequestParam` and not `Query`. This resulted in the UI playground for this endpoint choosing to type/present the `serviceAccount` parameter as the request body, which is not only wrong but would never work because it's a GET. This just switches to the other one, which I confirmed works as expected in the Swagger UI.

fix(managed): Use RequestParam instead of Query so Swagger UI does it right

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PagerDutyController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy

Add http methods to pipeline and pagerduty controllers so that we don't have all the possible http methods show up in swagger

fix(swagger): add explicit http methods

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/GoogleCloudBuildController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/BuildMasterNotFound.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/BuildService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/GCBAccountNotFound.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/GoogleCloudBuildTrigger.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/IgorService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/GoogleCloudBuildControllerSpec.groovy

Added ability to call existing GCB triggers.
This is part of: spinnaker/spinnaker#5076
Added new endpoint to `GoogleCloudBuildController` to fetch the list of `GoogleCloudBuildTriggers` from `igor`.
Modified `igor` service to add the corresponding endpoint.

feat(gcb): Ability to invoke existing GCB triggers

---

gate-ldap/gate-ldap.gradle
gate-ldap/src/main/groovy/com/netflix/spinnaker/gate/security/ldap/LdapSsoConfig.groovy

LDAP Logins when creating a cookie session don't set the samesite entry to null, thus LDAP logins are restricted to what are determined to be "Same sites".  This means when using AWS Load balanced hosts, you end up in an infinite loop.  This fixes this to match SAML & OAUTH configurations.

fix(ldap): Fix an issue where LDAP logins using SameSite cookies

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/SlackConfigProperties.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/SlackController.java

Slack is rate limiting our requests, and the channels do not update frequently. This PR:
1. Increase time between calls
2. Randomize initial delay to stagger the calls between instances and prevent rate limiting from Slack's API

fix(slack): Increase delay between scheduled calls to Slack API

---

build.gradle
gate-web/gate-web.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/Main.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/health/RedisRelaxedHealthIndicator.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/FunctionalSpec.groovy
gradle.properties

- See spinnaker/spinnaker#5134
- Dependent on spinnaker/kork#419 for a Spring Boot dependency upgrade
- Kotlin's reflection facilities needed by Spring are shipped in a separate JAR - https://kotlinlang.org/docs/reference/reflection.html
- `LdapHealthIndicatorAutoConfiguration` is no longer available in Spring Boot to 2.2.1

chore(dependencies): Upgrade Spring Boot to 2.2.1

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java

This sets up `ManagedController` to reflect the paused-related changes in https://github.com/spinnaker/keel/pull/644.
I yanked out the veto-related endpoints for now because they don't have a use, but would be happy to throw them back in if desired.

refactor(managed): switch from veto -> pause APIs

---

gate-basic/gate-basic.gradle
gate-basic/src/main/java/com/netflix/spinnaker/gate/security/basic/BasicAuthConfig.java

Fixes same issue had with LDAP - was missing the cookie serializer, so when gate & deck come up with different ALB's, you can't login without getting into an infinite loop.

fix(auth): Basic auth was missing the cookie serializer like other auth mechanisms

---

gate-web/src/main/java/com/netflix/spinnaker/gate/config/manageddelivery/DeliveryConfig.java
gate-web/src/main/java/com/netflix/spinnaker/gate/config/manageddelivery/Environment.java
gate-web/src/main/java/com/netflix/spinnaker/gate/config/manageddelivery/Notification.java
gate-web/src/main/java/com/netflix/spinnaker/gate/config/manageddelivery/Resource.java

Moving md model classes to gate, the only place they're used (@robfletcher is this an ok directory for them?). Removal of models from kork is in this pr: https://github.com/spinnaker/kork/pull/447.
Loosening the type of artifacts to be a map so we can support other properties on the artifact.

feat(md): move model classes to gate, update artifacts

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java

In pursuit of https://github.com/spinnaker/keel/issues/660 I'm removing the endpoints to create and delete individual resources.
I'll do the follow up work on keel after this.

chore(md): remove create/delete individual resource endpoints

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/Front50Service.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/V2PipelineTemplatesController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/V2PipelineTemplateService.java

https://github.com/spinnaker/spinnaker/issues/4670
This is part of a larger set of changes to support displaying versioned templates in the UI and Spin.
Related PRs:
[Deck](https://github.com/spinnaker/deck/pull/7708)
[Front50](https://github.com/spinnaker/front50/pull/658)
[Spin](https://github.com/spinnaker/spin/pull/235)

feat(core): Update Gate to return Map of versioned pipeline templates

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/Front50Service.groovy
gate-saml/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PluginController.java
gate-web/src/main/java/com/netflix/spinnaker/gate/config/SpinnakerExtensionsConfigProperties.java
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/PluginControllerSpec.groovy
gate-web/src/test/resources/gate-test.yml

- New API's to support Plugin metadata CRUD operations.
- All writes go through Orca (orchestration API's) 
- Read hits Front50.

feat(plugins): New API's to support plugin metadata CRUD operations

---

gate-deck-plugins/gate-deck-plugins.gradle
gate-deck-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/CacheNotReadyException.kt
gate-deck-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/DeckPluginCache.kt
gate-deck-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/DeckPluginConfiguration.kt
gate-deck-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/DeckPluginService.kt
gate-deck-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/DeckPluginVersion.kt
gate-deck-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/DeckPluginsController.kt
gate-deck-plugins/src/test/kotlin/com/netflix/spinnaker/gate/plugins/DeckPluginCacheTest.kt
gate-web/gate-web.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gradle/kotlin-test.gradle
settings.gradle

Depends on https://github.com/spinnaker/kork/pull/477
Adds support for serving Deck plugin assets, fixes spinnaker/spinnaker#5242.
All configured repositories (`spinnaker.extensibility.repositories`) are scanned for plugins and their latest release is downloaded and checked for deck plugin assets. Any plugin that has a deck component (`deck/index.js`) will be cached and returned when Deck requests a manifest or plugin asset.
Gate will return a `503 Service Unavailable` if these plugin endpoints are hit prior to the cache being populated. It's expected that Deck would retry on this error code.

feat(plugins): Deck plugin asset proxy

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/security/RequestContext.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/interceptors/RequestContextInterceptor.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/interceptors/RequestIdInterceptor.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/TaskService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OrcaServiceSelector.java
gradle.properties

This makes gate's RequestContext a readonly proxy to kork's AuthenticatedRequest. This is to avoid the situation where RequestContext and AuthenticatedRequest provide an inconsistent view of the context or lose it across thread boundaries.
This is a relatively big change, values in AuthenticatedRequest get propagated across threads and to downstream services in the form of X-SPINNAKER headers. So with this change, gate will now start emitting X-SPINNAKER-APPLICATION headers for instance (until now, only orca did that).

feat(context): replace RequestContext with AuthenticatedRequest

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/DynamicRoutingConfigProperties.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/LoadBalancerService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ByUserOriginSelector.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverServiceSelector.java
gate-web/src/test/groovy/com/netflix/spinnaker/gate/FunctionalSpec.groovy

Historically, ClouddriverServiceSelector was hardcoded to look only at the user origin (coming from the X-RateLimit-App header), and was able to look up a different url for clouddriver based on the value of that header.
With this PR, ClouddriverServiceSelector accepts a configurable SelectableService for which we can pass any number of criteria, similar to the existing pattern for e.g. orca and rosco. To avoid a breaking change, GateConfig will try to detect the previous clouddriver selector style (a `dynamicEndpoints` map) and configure an equivalent SelectableService. Additionally, we support a dynamic config to turn off routing at runtime if needed.
Note that RequestContext does not currently contain most criteria that gate can be configured to route on, will change this in an upcoming …

feat(clouddriver): make selector accept configurable criteria

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ByUserOriginSelector.java

GateConfig occasionally failed to intialize it with argument type mismatch (but hard to reproduce), I suspect it has to do with having multiple constructors and the use of reflection in
selectorClass.getConstructors()[0].newInstance(...)

fix(config): remove 2nd constructor from ByUserOriginSelector

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/interceptors/RequestContextInterceptor.java

AuthenticatedRequestFilter is responsible for it. Doing it in an interceptor means that other interceptors such as RequestLoggingInterceptor may get an empty context.

fix(context): don't clear the context in RequestContextInterceptor

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/model/manageddelivery/ConstraintState.java
gate-web/gate-web.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy

I "fixed" serialization by turning the `Instant`s into `String`s.
Why? I tried many different settings on the object mapper to get the instants to be written as the "nice" format (`2020-02-09T04:28:10Z`) but I could not figure it out.
So, I decided to change the type to String. I left the java time module on the object mapper though because it was shocking that wasn't already configured.

fix(md): serialize instants

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/NotificationService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/NotificationServiceSpec.groovy

For some reason Spring takes an empty string and converts it into a quoted empty string `""` in a `ResponseEntity`, which messes up rendering of the response in Slack. This ensures that's not the case.

fix(notifications): Ensure empty body on callback when appropriate

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CapabilitiesController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/EchoService.groovy

Adds an endpoint `GET: /capabilities/quietPeriod` that retrieves the current state of quiet period from `echo`
(see `echo` PR https://github.com/spinnaker/echo/pull/784)
The shape of the data returned is:
```
{
"startTime": 1581282000000,
"endTime": 1581339600000,
"enabled": true,
"inQuietPeriod": false
}
```
The idea is that `deck` could query this and warn the user when they are starting a pipeline within a quiet period

feat(quietperiod): expose current state of quiet period

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/AuthController.groovy

Currently, the implemented code returns `null` sometimes randomly because of accessing out of bound element. This commit fixes it.

fix(web): Fix logout message

---

gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/publish/PluginBinaryController.kt

AuthenticatedRequest.propagate returns a `Callable`, whoops.

fix(plugins): Invoke callable on propagated authentication

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java

Adding this API to gate so it can be used by external tooling like `newt` at Netflix or the `spin` CLI in OSS.
Note that this is different from `/managed/delivery-configs/diff` (which we'd been using for validation prior to this PR) in that it does not cause the fetching of data from clouddriver to compare desired with actual state. This strictly just validates the YAML/JSON of the delivery config.

feat(managed-delivery): Expose /managed/delivery-configs/validate API

---

gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/deck/DeckPluginsController.kt

We're using 30 days for regular deck assets at nflx, so let's start there for plugin assets.  these assets should be effectively  immutable based for a given url.

refactor: change deck assets cache control header to max-age of 30 days

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java

Fixes the `/managed/application` API per changes introduced in https://github.com/spinnaker/keel/pull/848

fix(managed-delivery): Fix application summary API

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java

It looks like `gate` doesn't have a YAML object mapper autowired into the Spring REST machinery, so error details returned from `keel` in YAML format were being dropped from the response. This forces the response from `keel` to be JSON so those details get included in `gate`'s response.

fix(managed-delivery): Allow parsing errors to be relayed

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/model/manageddelivery/Resource.java

When calling keel to POST a delivery config, and the submitted manifest is in YAML and omits the `metadata` field in resources, gate is converting the YAML to JSON and setting `metadata` to `null`, which breaks parsing in keel. This avoids including the field when it's `null`.

fix(managed-delivery): Avoid including null metadata

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java

Because this endpoint wasn't annotated properly, our auto-generated swagger UI was refusing to allow YAML request bodies in the example/playground. Should be behaviorally equivalent.

fix(managed): properly annotate YAML support on upsertManifest

---

Dockerfile.compile

This got missed because my script tries to add it before `--no-daemon`.
So go ahead and add that too, for consistency and because otherwise
GRADLE_OPTS does nothing useful.

chore(java11): Turn on the cross-compiler plugin in Dockerfile.compile

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy

We noticed that `ETag` filter somehow makes it so that requests from `gate` are no longer gzipped.
Since `deck` doesn't even use ETags, rather than figuring our what wrong with `ETag`s I am just removing them to get the gzip benefit (and stop wasting CPU cycles computing `ETag`s)

fix(etag): removing etag filter

---

gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/deck/DeckPluginConfiguration.kt
gradle.properties

Previous bumps were failing due to the constructor changing for `PluginBundleExtractor`.

chore(dependencies): Bump kork to 7.31.1 and fixup PluginBundleExtractor instantiation

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy

follow up from: https://github.com/spinnaker/gate/pull/1123
We noticed that `ETag` filter somehow makes it so that requests from `gate` are no longer gzipped.
Removing the filter caused the issue that responses no longer contained `Content-Length` header which means that the responses were chunked.
This is a pretty big difference and a breaking change for clients that might not be able to handle chunked responses.
This change sets the `ETag` to be weak which doesn't circumvent gzip but also sets the `content-length` and is thus not chunked.

fix(etag): produce weak ETag

---

gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/deck/DeckPluginConfiguration.kt
gradle.properties

This PR is part of a series of PRs for allowing relaxed plugin loading by adding a config option to turn strict plugin loading on or off. See https://docs.google.com/document/d/1yFDrpkCCV7Vp0wN0gDc9GTbTOBoIzNo-tGj1-vVjq04/edit?usp=sharing for more info

fix(plugins): add an option for strict plugin loading

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/config/AuthConfig.groovy
gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/PermissionService.groovy
gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/ServiceAccountFilterConfigProps.java
gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ExtendedFiatService.java
gate-core/src/test/groovy/com/netflix/spinnaker/gate/services/PermissionServiceSpec.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/AuthController.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/basic/BasicAuthSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/ldap/LdapAuthSpec.groovy

enables a more meaningful list of service accounts when selecting a run as user
This feature can be disabled by setting `fiat.service-accounts.filter.enabled=false`.
The required authorizations for the service account on the application can be customized,
by default they are either of WRITE or EXECUTE, but can be set as
`fiat.service-accounts.filter.match-authorizations=READ,WRITE,EXECUTE`
In the event that no service accounts match the specific application, the user's full
list of service accounts is returned as a fallback.

feat(serviceAccounts): filter service accounts by application

---

build.gradle
gate-api/src/main/java/com/netflix/spinnaker/gate/api/extension/ApiExtension.java
gate-api/src/main/java/com/netflix/spinnaker/gate/api/extension/HttpRequest.java
gate-api/src/main/java/com/netflix/spinnaker/gate/api/extension/HttpResponse.java
gate-proxy/gate-proxy.gradle
gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/ApiExtensionController.kt
gate-proxy/src/test/kotlin/com/netflix/spinnaker/gate/controllers/ApiExtensionControllerTest.kt
gate-web/gate-web.gradle

This implementation is similar to that of the `ProxyController` and allows for
new endpoints to be exposed under the `/extensions/{id}/**` path.

feat(api): An `ExtensionPoint` that allows plugin endpoints to be exposed under a common path

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/filters/ContentCachingFilter.java

Add a content caching filter instead of the `ETag` filter so that we:
a) don't have to waste CPU cycles computing MD5 hashes
b) but still set `Content-Length` on the response to avoid chunked transfers

fix(etag): remove etag filter

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/model/manageddelivery/EnvironmentArtifactVeto.java
gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java

Exposing veto endpoints that were moved by this PR (https://github.com/spinnaker/keel/pull/1022).
Updating pin endpoints to no longer accept the artifact type, because it's no longer needed (change done https://github.com/spinnaker/keel/pull/1014).
I'll wait to merge until both of those PRs are in.

feat(md): expose veto endpoints

---

gate-api/src/main/java/com/netflix/spinnaker/gate/api/extension/ApiExtension.java

Under the hood, this means we're proxying extensions again.
@ajordens After this merges (and deploys), try adding `@Metered` to your plugin's ApiExtension `handle` method.

chore(plugins): Replace PF4J ExtensionPoint with SpinnakerExtensionPoint

---

gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/ProxyController.kt

We've run into a use case where more request methods would help, AFAICT this should be all that's needed given we handle request bodies/etc. already.

feat(proxy): add PUT and DELETE to allowed proxy methods

---

gate-web/config/gate.yml
halconfig/README.md
halconfig/gate.yml

The redis url is being set in the Halyard-specific file that is concatenated to the config; let's just move that defaulting to the base gate.yml.
This should not cause any visible change to non-Halyard users, as we are defaulting back to the same localhost:6379 if the redis override is not defined. It will also not affect Halyard users as it's just changing where we set this value for them.

config(core): Push Halyard config to base

---

gate-oauth2/gate-oauth2.gradle

SimpleXML converter was deprecated by Retrofit due to CVE-2017-1000190
So I removed converter-simplexml as this lib is no longer being used and no action is required to replace it.
Dependency was introduced in this PR https://github.com/spinnaker/gate/commit/0732238f9f5ea0b49d31bd1cba9c4fc8a48f5e63 used to call old GitHub endpoints that required XML conversion.

chore(oauth2): remove converter-simplexml lib.

---

gate-oauth2/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServices.groovy
gate-oauth2/src/test/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServicesSpec.groovy
gradle.properties

Azure AD (and other OAuth2.0 providers, perhaps) return roles as an array with a single string entry, where the string is a JSON-formatted array:
```json
["[\"0af94c47-f083-42cf-b1c6-9b0d4871b704\",\"d094e693-ae79-4e3c-8590-3d60d304fc50\",\"66ed6631-e6ac-4a27-a015-47a253ad2439\"]"]
```
The current parsing of roles results in this being a single role, which is a long string:
```json
"[\"0af94c47-f083-42cf-b1c6-9b0d4871b704\",\"d094e693-ae79-4e3c-8590-3d60d304fc50\",\"66ed6631-e6ac-4a27-a015-47a253ad2439\"]"
```
This code introduces detection of this one specific edge case (if the first 'role' in the array starts with the character `[` or `{`), and uses the Groovy JsonSlurper package to parse it into a Groovy object.
Roles before the change:
Roles after the change:

fix(oauth2): Handle oddly-formatted roles userInfo

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/KeelService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
gate-web/src/main/java/com/netflix/spinnaker/gate/config/SwaggerEndpointsConfig.java

Integrates the keel endpoint for Swagger API docs so that it can be selected from the "Select a spec" drop-down on the Swagger UI hosted by gate, and keel's API docs displayed on that UI.

docs(managed-delivery): Integrate keel API docs into Swagger

---

gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/deck/DeckPluginConfiguration.kt
gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/deck/DeckPluginsController.kt

`@ComponentScan` strikes again, the bean factory method is totally useless.

fix(plugins): Start without deck caching enabled

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/DataController.groovy

Suspect this broke in one of the Spring Boot 2.x upgrades.
It's likely possible to revisit the streaming responses but the
usefulness of these endpoints never materialized beyond a handful
of use-cases at Netflix (afaik).
This at least "fixes" these endpoints such that they'll return
results again.

fix(web): Unwinds the streaming responses in `DataController`

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/NotificationService.groovy

I added quite a lot of logging around notification callbacks when I initially rolled this out, but obviously not in the one place where we're seeing an issue now. 😝 
This PR adds debug logging around building the proxy request to echo on callbacks, and also adds a bit of additional error handling for retrofit errors such that we hopefully return a better response in error cases.

debug(notifications): Improve debug logging for notification callbacks

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/security/anonymous/AnonymousConfig.groovy
gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/DefaultProviderLookupService.groovy
gate-iap/src/main/java/com/netflix/spinnaker/gate/security/iap/IapAuthenticationFilter.java
gate-oauth2/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServices.groovy
gate-oauth2/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/provider/GithubProviderTokenServices.groovy
gate-saml/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/AuthController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
gate-x509/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsService.groovy

Prefer log formatting (`{}`) over string concatenations or groovy formatting. Pass the whole exception to the logger instead of trying to extract the message, class or stack trace. If you get an exception, log it or throw it.

chore(logs): be more consistent with exception logging

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ApplicationController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PagerDutyController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ApplicationServiceSpec.groovy

So that /applications/* gets the same clouddriver sharding treatment as every other.
Also some opportunistic log cleanup.

fix(applications): use a clouddriver service selector

---

gate-web/gate-web.gradle

This protects us from the scenario wherein the Implementation-Version set for a test actually ends up being the version used in a final JAR artifact (since Gradle does not re-compile the JAR after it has been compiled for a test task).

fix(build): Do not set Implementation-Version in test JAR if already set to a valid version

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy

The current swagger client is broken due to HttpEntity being interpreted as a json struct rather than a flat representation of the body class member. 
This api returns responses in the format:
```
{"eventId":"xxxxx","ref":"/pipelines/xxxxx"}
```
Swagger expects:
```
{"body":{}}
```
Gave Swagger a return type hint of Map, which maps properly with the proper return format.

chore(swagger): add proper return type for invokePipelineConfigViaEcho

---

gate-saml/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy

When Spinnaker is configured with SAML authentication, the `SAMLRequest` is always signed with the `SHA1` digest algorithm (`SignatureMethod` and `DigestMethod` of the request):
```
<?xml version="1.0" encoding="UTF-8"?>
<saml2p:AuthnRequest xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" AssertionConsumerServiceURL="http://localhost:8084/saml/SSO" Destination="https://armory.okta.com/app/armory_germansamltest_1/exk7nc0r0hHggwnG32p7/sso/saml" ForceAuthn="false" ID="a3a56cde732h83fd5a8gh0cd7j15h14" IsPassive="false" IssueInstant="2020-07-01T19:16:17.698Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0">
<saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">io.armory.spinnaker.german</saml2:Issuer>
<ds:Signature …
```

feat(authn/saml): Configurable signature digest algorithm

---

gate-web/src/test/groovy/com/netflix/spinnaker/gate/FunctionalSpec.groovy

This bean definition is required for the kork(`kork-retrofit`) changes

add bean dependency in functional spec

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/PostConnectionConfiguringJedisConnectionFactory.java

Follow Kork's existing pattern and check for presence of `rediss` in
the URI Scheme.
Gate doesn't initialise JedisPool() pool with parameters like Kork
so follow Gate conventions and use function to enable SSL.
Tested with default redis configuration and in-cluster (kubernetes) Redis (no auth or tls).
Also tested against Elasticache Redis with below gate.yml snippet with token mounted to container as env var:
```
services:
redis:
baseUrl: rediss://:${REDIS_TOKEN}@master.<snip>.cache.amazonaws.com:637
9
redis:
configuration:
secure: true
```
Related to: spinnaker/spinnaker#5470

feat(gate): Add support for Redis SSL

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/model/manageddelivery/ConstraintStatus.java

We recently added the `artifactReference` field into `ConstrainStatus` model, in order to have a unique artifact identifier.
This PR is followed by https://github.com/spinnaker/deck/pull/8485 for deck
and https://github.com/spinnaker/keel/pull/1399 in keel.

fix(artifactReference): add artifactReference field into ConstrainStatus model

---

gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/web/info/PluginInfoController.kt

When running swagger to update the Spin CLI to latest gate code for https://github.com/spinnaker/spin/pull/294 and https://github.com/spinnaker/spinnaker/issues/5967 the following change needed to accommodate changes from https://github.com/spinnaker/gate/pull/1307

fix(getAllPluginInfo): fix return type

---

gate-plugins-test/src/main/kotlin/com/netflix/spinnaker/gate/plugins/GateApiExtension.kt
gate-plugins-test/src/test/resources/gate-plugins-test.yml

Just a minor tweak, seems like a decent thing to test.

fix(plugins): Load ApiExtension config property from service yml in gate-plugins-test

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/filters/RequestLoggingFilter.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/filters/RequestTimingFilter.java

The `RequestLoggingFilter` has always run after the security filter chain
_and_ the `AuthenticatedRequestFilter`.
This unfortunately had a side-effect of the tracked duration not reflecting
time spent during the authentication flow.
By introducing a new higher priority filter, we can capture an accurate
start time for a request as well as have a request id that can be
propagated throughout the entire lifetime of a request. The latter is
a helpful debugging technique.

feat(logging): Ensure that request duration reflects the entire request

---

gate-x509/src/main/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsService.groovy
gate-x509/src/test/groovy/com/netflix/spinnaker/gate/security/x509/X509AuthenticationUserDetailsServiceSpec.groovy

the login debounce check was calling fiat /authorize if the user was not cached, and doing so without supplying an X-SPINNAKER-USER
this would 404 if the user needs to log in, and trigger the exponential backoff in fiat permission evaluator

fix(x509/authn): improve login debounce performance

---

gate-proxy/gate-proxy.gradle
gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/ProxyController.kt

Using a simple `CacheBuilder` to ensure that all `ProxyConfig` objects
are only initialized _once_.

feat(proxy): Handle delayed initialization of proxy configurations

---

gate-api/src/main/java/com/netflix/spinnaker/gate/api/extension/ProxyConfig.java
gate-proxy/gate-proxy.gradle
gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/Proxy.kt
gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/ProxyController.kt

This PR moves away from using our own hand rolled `OkHttpClient` in favor
of what `OkHttpClientProvider` provides.
A few attributes have been removed from `ProxyConfig` that I believe were
only used by Netflix.
If we need to support custom keystore/truststore behaviors, we should do
so by implementing a custom `OkHttpClientBuilderProvider`.

feat(proxy): Migrate to `okhttp3`

---

gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/Proxy.kt

The `DefaultOkHttpClientBuilderProvider` (previous behavior) will actually
utilize the `okHttpClient.*` config properties and unnecessarily set
keystore/truststores.
This is fine when communicating with other Spinnaker services but problematic
externally. The `InsecureOkHttpClientBuilderProvider` loosens the certificate
chain validations.

fix(proxy): Take advantage of `InsecureOkHttpClientBuilderProvider`

---

gate-api/src/main/java/com/netflix/spinnaker/gate/api/extension/ProxyConfig.java
gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/Proxy.kt

s/Object/String, we can revisit should we need to store more than
simple Strings.

feat(proxy): Slight tightening of the `ProxyConfig` contact.

---

build.gradle
gate-web/gate-web.gradle

This doesn't need to be on every classpath, it happens at runtime during app startup

fix(libs): move properties migrator to runtimeOnly of web

---

gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/deck/DeckPluginCache.kt
gate-plugins/src/main/kotlin/com/netflix/spinnaker/gate/plugins/deck/DeckPluginConfiguration.kt
gate-plugins/src/test/kotlin/com/netflix/spinnaker/gate/plugins/deck/DeckPluginCacheTest.kt
gradle.properties

When the service starts up, the `DeckPluginCache` download the deck plugins and add them to the cache, then it serves these plugins to `Deck` service
We want to bake deck plugins in this cache, in order to provide the plugin assets and avoid download them.
This PR include an extra configuration property `spinnaker.extensibility.deck-proxy.plugins-path` on the cache and when it is present the `DeckPluginCache` will store downloaded plugins on the given directory.
Make the cache directory configurable, we will be able to copy the plugin assets that we want to bake for `Deck`.
if the new configuration property is not provided, all the downloaded plugins will be stored in a temporary directory.

feat(cache): Configurable directory for deck plugin cache

---

gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/KeelService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java

New endpoint so that browsers can be forced to show YAML without messing with the `Accept` header

allow retrieval of resources in YAML format

---

gate-core/src/main/java/com/netflix/spinnaker/gate/services/TaskService.java

because
```java
i = i++;
```
is a noop and `i` will never increment

fix(api): don't poll forever

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/filters/RequestSheddingFilter.java
gate-web/src/test/groovy/com/netflix/spinnaker/gate/filters/RequestSheddingFilterSpec.groovy

The explicit `.setStatus` could be swapped out for an exception provided the following config was used:
```
spring:
security:
filter:
dispatcherTypes: async, request
```
Removing `error` from `dispatcherTypes` prevents the spring security filter chain from
evaluating during the `/error` redirect.

feat(web): request shedding is now filter-based and checked before the spring security filter chain is evaluated

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/filters/RequestSheddingFilter.java

Previous change was missing a closing `}` on the hand rolled json.

feat(web): Return proper json from the `RequestSheddingFilter`

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingFilter.java

ie. Don't expect there to always be x509 certificates present.

fix(web): `RateLimitingFilter` should handle non-ssl requests

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/filters/RequestLoggingFilter.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/filters/ResetAuthenticatedRequestFilter.java

In `gate`, the `RequestLoggingFilter` has support for clearing the
`AuthenticatedRequest`.
This preserves the `X-SPINNAKER-*` MDC values and allows them to be correctly logged.

fix(web): `AuthenticatedRequestFilter` should not clear the `AuthenticatedRequest`

---

gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/ClouddriverService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/RawResourceController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/RawResourceService.java

It serves all resources regardless of their Spinnaker kind
For context, see this PR: https://github.com/spinnaker/clouddriver/pull/5057

feat(web): Add the rawResources clouddriver endpoint

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ApplicationController.groovy

We always fetch user permission in bulk for auth checks making this
PreAuthorize header unnecessary

fix(authz): remove unneeded storeWholePermission

---

gate-api-tck/src/main/resources/gate-test-app.yml
gate-core/src/main/groovy/com/netflix/spinnaker/gate/config/AuthConfig.groovy
gate-plugins-test/src/test/resources/gate-plugins-test.yml
gate-plugins/src/test/resources/gate-test.yml
gate-web/config/gate.yml
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/NotificationController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/NotificationService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/services/NotificationServiceSpec.groovy
gate-web/src/test/resources/gate-test.yml

Adding a new endpoint to support callbacks for managed-delivery specific notifications. 
The new endpoint will use the existing service implementation to parse the request and delegate it to `keel` directly, as opposed to using the mid-layer currently in `echo`.

feat(slackV2): add new endpoint for keel specific slack callbacks

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java

Changing the default format to HTML now that keel supports it.

feat(managed-delivery): Make HTML the default report format

---

gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/KeelService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ManagedController.java

Our REST controllers and Retrofit clients, as configured, default to trying to parse/return JSON, and so without using response wrappers this new keel endpoint fails. This PR fixes that for the adoption report endpoint by using the same approach as for the onboarding report.

fix(managed-delivery): Fix adoption report endpoint

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/SlackController.java

This PR introduces retries (w/ backoff) around the calls to fetch
`conversations.list` from Slack.

fix(slack): Use the 'retry-after' header to control retries after rate limit

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/V2PipelineTemplateService.java

Hello,
`toArray()` instantiates an Array of Objects, and cannot be type cast to `String[]`
Related:
https://github.com/spinnaker/spinnaker/issues/6003
Thanks!

fix(pipeline-templates): fix ClassCastException

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/config/AuthConfig.groovy
gate-core/src/test/groovy/com/netflix/spinnaker/gate/config/AuthConfigTest.groovy

Currently the `/webhooks/**` endpoint is unauthenticated. @aelath and I discovered that we need the ability to force authentication for POST requests to this specific endpoint, so we added a setting in the `AuthConfig` class to do so. This is to ensure that POSTs to `/webhooks/**` will be authenticated with the default authentication Gate is configured for (basic auth, x509, etc). 
In the future, webhooks could possibly have their own security settings if a different authentication method is preferred than the default auth, but that is not part of this PR.
See the below `gate.yml` config for how to enable authentication for webhooks with this change:
```
security:
webhooks:
defaultAuthEnabled: true
```
The webhooks endpoint will otherwise be unauthenticated without this setting.

feat(auth): Make webhooks endpoint configurable for authentication

---

gate-iap/gate-iap.gradle

This is a clean up activity after introducing [CVE-2019-17195](https://nvd.nist.gov/vuln/detail/CVE-2019-17195) fix in kork.

fix(vulnerability): Remove fixed version of com.nimbusds:nimbus-jose-jwt dependency to accommodate safer version from kork.

---

build.gradle
gate-api/gate-api.gradle
gate-basic/gate-basic.gradle
gate-bom/gate-bom.gradle
gate-core/gate-core.gradle
gate-iap/gate-iap.gradle
gate-integrations-gremlin/gate-integrations-gremlin.gradle
gate-ldap/gate-ldap.gradle
gate-oauth2/gate-oauth2.gradle
gate-plugins-test/gate-plugins-test.gradle
gate-plugins/gate-plugins.gradle
gate-proxy/gate-proxy.gradle
gate-saml/gate-saml.gradle
gate-web/gate-web.gradle
gate-x509/gate-x509.gradle
gradle.properties

There is an issue in the Deck cache of Gate that was solved in this PR: https://github.com/spinnaker/kork/pull/866
but this fix was released in kork 7.110.0
I bumped the version of kork to include the fix in Gate but this involved changing the groupId of kork because now it's been published under "io.spinnaker" and this release branch is pretty old.
I had to bump the version of Fiat as well because it has issues when trying to download the kork version in fiat due to the groupId change.

chore(build): upgrade kork & fiat version, use new groupId

---

gate-oauth2/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/ExternalAuthTokenFilter.groovy
gate-oauth2/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuth2SsoConfig.groovy
gate-web/gate-web.gradle
gate-web/src/test/groovy/com/netflix/spinnaker/gate/security/oauth2/OAuth2Spec.groovy

Previously in spring 2.2.5, if oauth2 is enabled there is no circulardependency on ExternalAuthTokenFilter bean in OAuth2SsoConfig.
In spring 2.2.13, if oauth2 is enabled there is a circular dependency error on ExternalAuthTokenFilter bean. This circular dependency results in an error when the gate application tries to start up. The application fails with error:
```
BeanCurrentlyInCreationException: Error creating bean with name
'OAuth2SsoConfig': Bean with name 'OAuth2SsoConfig' has been injected into other beans [externalAuthTokenFilter] in its raw version as part of a circular reference, but has eventually been wrapped.
```
To fix this error, add the Component annotation to
ExternalAuthTokenFilter and remove the ExternalAuthTokenFilter bean
from OAuth2SsoConfig.
**Note**: This fix was …

fix(oauth): remove circular dependency on ExternalAuthToken in OAuth2SsoConfig when oauth2 is enabled

---

gate-web/config/gate.yml

We don't need `keel.enabled=true` to `gate-web/config/gate.yml` since keel service is optional.

fix(web): disable keel by default since it is an optional service

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/AuthController.groovy

Movie quotes had miss wordings.  This could cause major outrage for users... 😄

fix(api): movie quotes in LOGOUT_MESSAGES

---

gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/ClouddriverService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CredentialsController.groovy

This adds some of the REST APIs introduced in the experimental account
storage API in Clouddriver to Gate. Initially, these APIs are only
available for admins.
https://github.com/spinnaker/spinnaker/issues/6525
Requires https://github.com/spinnaker/clouddriver/pull/5594

feat(web): Expose experimental account storage API

---

gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/ClouddriverService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CredentialsController.groovy

- Fixes a security annotation on the credentials controller.
- Fixes a retrofit error in Clouddriver proxy.

fix(gate): Typos in Account Management API

---

gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/ClouddriverService.java

This fixes an authorization check error where Jackson knows how to
handle the `name` property of an account definition, but SpEL does
not see the property. Now the PostFilter annotation should work
equivalently to the same filter check in Clouddriver.
Related to updates for https://github.com/spinnaker/spinnaker/issues/6525

fix(gate/web): Add explicit name property to AccountDefinition

---

gate-core/src/main/groovy/com/netflix/spinnaker/gate/config/AuthConfig.groovy

During setup of spinnaker authentication with oauth2 a common hurdle is a redirect loop.
For example:
https://github.com/spinnaker/spinnaker/issues/5794
https://github.com/spinnaker/spinnaker/issues/1630
Also, many threads in Slack discuss these problems. In fact this appears to be a common
pitfall for the spring-security-oauth2-autoconfigure library in general. A light refresher
on the ouath2 flow in play here seems worthwhile. The user is redirected from `/login` in gate
to the external auth provider (google, github, etc.) and after successfully authenticating
they are redirected back to the gate `/login` endpoint but this time with a code parameter
that is to be used to request an access token.
This request can fail for a variety of reasons, and if it does, the underlying spring …

fix(authn/oauth2): prevent oauth2 redirect loops

---

build.gradle
gradle.properties

Spring boot has moved to gradle based dependency management from v2.3.x. This change has brought issue of conflict resolution failure of the Jackson-bom version and kotlin-bom version with gate service when it consumes the maven-bom generated by kork. The issue details are available in given link.
https://docs.google.com/document/d/1Ck4KeoB1ER0aQUTnf3e-x-M3i2Ur0It7YaaxEMiMXls/edit
To resolve this issue while upgrading gate service with spring v2.3.x, we must require the spring dependency management gradle plugin.

fix(dependency): Issue with jackson-bom and kotlin-bom version conflict resolution while upgrading the spring-boot 2.3.x

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml

I wanted to avoid confusion between a git tag `X` building version `X` and a
master or release branch building version `X-dev-*` but it seems unavoidable.
SemVer is required by plugins.
See constraint: https://github.com/spinnaker/kork/blob/5dc6bb98615667f1b4f3e18445c1651d773c9f6b/kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpinnakerServiceVersionManager.kt#L47
changes:
- fetch full git repository so that we can access previous tag in branch.
Convert `release.yml` to this method instead of `run: git.. --unshallow`.
- use previous git tag as start of version string. Cut the 'v' prefix from the
tag, 'v1.2.3' -> '1.2.3' as required for Plugins (and Debians fwiw):
`Caused by: Unexpected character 'LETTER(v)' at position '0', expecting '[DIGIT]'`
- append …

chore(cit): GHA - plugin builds require SemVer

---

gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/ClouddriverService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CredentialsController.groovy

This normalizes the type discriminator in account definitions to match that of account credentials instances (i.e., the type of CredentialsDefinition instance and Credentials instance are both specified through the "type" property). See https://github.com/spinnaker/clouddriver/pull/5666 for corresponding update.
This also removes redundant authorization annotations that are better enforced by AccountDefinitionService in Clouddriver.

feat(credentials): Update account type discriminator

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml

to see if (transient?) failures like https://github.com/spinnaker/gate/actions/runs/3595421934/jobs/6054889075 stop happening.
There are also some deprecation warnings like:
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
that this addresses.

chore(gha): bump versions of github actions

---

gate-web/gate-web.gradle

The properties spring.config.additional-location and spring.profiles.active are redundant in gate-web.gradle file. These properties are set by class com.netflix.spinnaker.kork.boot.DefaultPropertiesBuilder in com.netflix.spinnaker.gate.Main. So removing it from gradle file.

refactor(web): Clean up redundant spring property in gradle file

---

build.gradle
gate-oauth2/gate-oauth2.gradle
gate-web/gate-web.gradle

with a specific goal to get `org.testng:testng:7.4.0` out of shipping code, since it's vulnerable to CVE-2022-4065.

chore(dependencies): remove dependency on groovy-all

---

gate-web/gate-web.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/Main.groovy

Using `com.netflix.spinnaker.kork.boot.DefaultPropertiesBuilder` class to setup spring and other related properties required for the spring boot application to start.

chore(web): clean up for spring property setup

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ArtifactController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ArtifactService.java
gate-web/src/test/java/com/netflix/spinnaker/gate/controllers/ArtifactControllerTest.java

Refactor code for the /artifacts/fetch api so that close() on the InputStream object is called. Add unit test for verification.

fix(web): Fixes ArtifactController and ArtifactService to close the InputStream object used in the fetch api and add unit test for controller

---

gate-web/src/test/java/com/netflix/spinnaker/gate/interceptors/ResponseHeaderInterceptorTest.java

Remove AuthenticatedRequesterFilter usage from ResponseHeaderInterceptorTest as they are not necessary.

refactor(web): Remove unnecessary code from ResponseHeaderInterceptorTest

---

gate-web/gate-web.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/test/java/com/netflix/spinnaker/gate/config/GateConfigAuthenticatedRequestFilterTest.java

This is done by setting the extractSpinnakerHeaders flag to true when creating the AuthenticatedRequestFilter in GateConfig. This allows the propagation of request headers with X-SPINNAKER prefix downstream through the AuthenticatedRequest MDC for consumption e.g. response interceptor

feat(web): Enable extracting Spinnaker related headers from request into authenticated request MDC

---

build.gradle
gate-plugins-test/gate-plugins-test.gradle
gate-plugins/gate-plugins.gradle
gate-web/gate-web.gradle
gradle/kotlin-test.gradle

Spring boot 2.4.x removed JUnit5 vintage engine from spring-boot-starter-test. [https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#junit-5s-vintage-engine-removed-from-spring-boot-starter-test] It is required for executing junit4 based test cases in gate. So, introducing junit-vintage-engine dependency in build.gradle, using testRuntimeOnly() as suggested in section 3.1 of https://junit.org/junit5/docs/5.6.2/user-guide/index.pdf
After applying this fix, coverage increased from 74 to 265 test case executions.

fix(tests): Introduce junit5 vintage engine for running junit4 test cases over junit5 in gate

---

gate-web/src/test/java/com/netflix/spinnaker/gate/testconfig/GateConfigAuthenticatedRequestFilterTest.java

so it doesn't pollute the spring context in other tests

fix(web/test): move GateConfigAuthenticatedRequestFilterTest out of the com.netflix.spinnaker.gate.config package

---

gate-web/src/test/groovy/com/netflix/spinnaker/gate/FunctionalSpec.groovy

There's a window in time between closing the socket and starting the server that another
process could use the same port.  Remove this race to prevent failures like:
```
FunctionalSpec > should call ApplicationService for applications FAILED
org.gradle.internal.exceptions.DefaultMultiCauseException: Multiple Failures (2 failures)
org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.PortInUseException: Port 59629 is already in use
java.lang.NullPointerException: Cannot invoke method close() on null object
at org.junit.vintage.engine.execution.TestRun.getStoredResultOrSuccessful(TestRun.java:196)
at org.junit.vintage.engine.execution.RunListenerAdapter.fireExecutionFinished(RunListenerAdapt …
```

fix(web/test): remove race in FunctionalSpec

---

settings.gradle

With gradle 6.x, used [feature preview API](https://docs.gradle.org/7.6.1/userguide/feature_lifecycle.html#feature_preview) to take advantage of [improvised dependency version ordering](https://docs.gradle.org/6.5/release-notes.html#improved-dependency-version-ordering). This feature is made public for gradle 7.x. So, removing it from settings.gradle as we moved to gradle 7.6.1

cleanup(preview): remove preview feature of version ordering (VERSION_ORDERING_V2) for gradle dependencies

---

gate-core/gate-core.gradle
gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/ClouddriverService.java
gate-web/gate-web.gradle
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ArtifactController.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ArtifactService.java

This commit adds new endpoints and connections to the various services that require direct retrieval of the artifact, eg deck will now lazily load by calling the gate fetch artifact endpoint.
Depends on https://github.com/spinnaker/clouddriver/pull/5976

feat(artifacts): Add new ArtifactStore endpoints

---

gate-core/src/test/java/com/netflix/spinnaker/gate/services/TaskServiceTest.java
gate-plugins-test/gate-plugins-test.gradle

Before refactor, total test cases executed were 266. 
After refactor, total test cases executed are 266.

refactor(tests): convert junit4 based test cases to junit5 and clean up in gate

---

gate-web/src/test/groovy/com/netflix/spinnaker/gate/MainSpec.java
gate-web/src/test/java/com/netflix/spinnaker/gate/controllers/ArtifactControllerTest.java
gate-web/src/test/java/com/netflix/spinnaker/gate/interceptors/ResponseHeaderInterceptorTest.java
gate-web/src/test/java/com/netflix/spinnaker/gate/testconfig/GateConfigAuthenticatedRequestFilterTest.java

Used assertThat() to cleanup junit4 linkages. Introduced explicit mocks to reduce dependence on `spockframework`/`groovy` transformations used by groovy based test under same package. Test coverage remain same before and after refactor (Tests executed 268).

refactor(web/test): replace assert with assertThat and introduce explicit mocks

---

gate-web/gate-web.gradle

With groovy 2.5.15 and spockframework 1.3-groovy-2.5, groovy-json appear as transitive dependency of [spockframework](https://mvnrepository.com/artifact/org.spockframework/spock-core/1.3-groovy-2.5) as shown below:
```
$ ./gradlew gate-web:dI --dependency groovy-json --configuration testCompileClasspath
> Task :gate-web:dependencyInsight
org.codehaus.groovy:groovy-json:2.5.15
Variant compile:
| Attribute Name                 | Provided | Requested         |
|--------------------------------|----------|-------------------|
| org.gradle.status              | release  |                   |
| org.gradle.category            | library  | library           |
| org.gradle.libraryelements     | jar      | classes+resources |
| org.gradle.usage               | java-api | java-api          |
| …
```

chore(dependency): add explicit dependency of groovy-json in gate-web while upgrading groovy 3.x

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
Dockerfile.java11.slim
Dockerfile.java11.ubuntu
Dockerfile.slim
build.gradle
gate-plugins/src/test/kotlin/com/netflix/spinnaker/gate/plugins/deck/DeckPluginCacheTest.kt
gate-web/src/test/groovy/com/netflix/spinnaker/gate/FunctionalSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/WebhookControllerSpec.groovy

* Add boilerplate to run tests with JRE 17 + build JRE 17 images.
* Add Jackson converters to `RestAdapter`s that don't have one already.
* Refactor a test case to not mock `Files`.

JRE 17 config for Gate

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy

While upgrading springboot 2.5.15, encounter below error in gate-web module:
```
startup failed:
/gate/gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy: 231: [Static type checking] - Cannot call com.netflix.spinnaker.kork.web.selector.SelectableService#<init>(java.util.List <com.netflix.spinnaker.kork.web.selector.ServiceSelector>) with arguments [java.util.List <? extends com.netflix.spinnaker.kork.web.selector.ServiceSelector>]
@ line 231, column 9.
new SelectableService(selectors + defaultSelector), dynamicConfigService, contextProvider)
^
/gate/gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy: 322: [Static type checking] - Cannot find matching method java.lang.Object#configure(com.fasterxml.jackson.databind.SerializationFeature, …
```

refactor(web): fix groovy compilation failure due to missing type conversions during upgrade to springboot 2.5.15

---

gate-core/src/main/java/com/netflix/spinnaker/gate/services/PermissionService.java

This fixes a regression from when PermissionService was converted from Groovy to Java. Ideally, we'd remove the extra parameter from FiatService directly, but that requires patching Fiat first, something that'll be easier to do when we migrate to the monorepo.
Fixes [#6887](https://github.com/spinnaker/spinnaker/issues/6887).

fix(core): RetrofitError thrown on login

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/RedisConfigSecure.java

gate is failing with the following error when you set `redis.configuration.secure=true`
```
***************************
APPLICATION FAILED TO START
***************************
Description:
The dependencies of some of the beans in the application context form a cycle:
┌─────┐
|  gateConfig defined in file [/Users/nemesis/opsmx/source/oss/gate/gate-web/build/classes/groovy/main/com/netflix/spinnaker/gate/config/GateConfig.class]
↑     ↓
|  postConnectionConfiguringJedisConnectionFactory defined in file [/Users/nemesis/opsmx/source/oss/gate/gate-web/build/classes/groovy/main/com/netflix/spinnaker/gate/config/PostConnectionConfiguringJedisConnectionFactory.class]
└─────┘
```

fix(redis): circular dependencies

---

gate-web/src/test/groovy/com/netflix/spinnaker/gate/FunctionalSpec.groovy

When they leak, other tests fail with errors like:
```
MainSpec > startupTest() FAILED
java.lang.IllegalStateException: Failed to load ApplicationContext
at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132)
at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124)
at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)
at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)
at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:248)
at …
```

fix(web/test): stop leaking system properties from FunctionalSpec

---

gate-web/src/test/java/com/netflix/spinnaker/gate/interceptors/ResponseHeaderInterceptorTest.java

While upgrading junit to 5.9.0, encountered below error during test execution of gate-web module:
```
@BeforeEach method 'private void com.netflix.spinnaker.gate.interceptors.ResponseHeaderInterceptorTest.setup()' must not be private.
org.junit.platform.commons.JUnitException: @BeforeEach method 'private void com.netflix.spinnaker.gate.interceptors.ResponseHeaderInterceptorTest.setup()' must not be private.
at org.junit.jupiter.engine.descriptor.LifecycleMethodUtils.assertNonPrivate(LifecycleMethodUtils.java:104)
at org.junit.jupiter.engine.descriptor.LifecycleMethodUtils.lambda$findMethodsAndAssertNonStaticAndNonPrivate$2(LifecycleMethodUtils.java:74)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections …
```

refactor(test): fix scope of setup method while upgrading junit to 5.9.0

---

gate-basic/gate-basic.gradle
gate-basic/src/main/java/com/netflix/spinnaker/gate/security/basic/BasicAuthConfig.java
gate-core/src/main/java/com/netflix/spinnaker/gate/config/AuthConfig.java
gate-core/src/main/java/com/netflix/spinnaker/gate/config/MultiAuthSupport.java
gate-web/src/test/java/com/netflix/spinnaker/gate/AuthConfigTest.java
gate-web/src/test/java/com/netflix/spinnaker/gate/MultiAuthSupportTest.java

to prevent
```
java.lang.UnsupportedOperationException: public abstract int javax.servlet.ServletRequest.getLocalPort() is not supported 
```
and HTML response bodies like:
```
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1>
instead of json when processing errors.
```
See https://github.com/spring-projects/spring-security/issues/11055#issuecomment-1098061598 for background.
https://github.com/spinnaker/gate/pull/1817 is a similar …

fix(core): remove ErrorPageSecurityFilter bean named errorPageSecurityFilter

---

gate-basic/gate-basic.gradle
gate-basic/src/main/java/com/netflix/spinnaker/gate/security/basic/BasicAuthConfig.java
gate-core/src/main/java/com/netflix/spinnaker/gate/config/AuthConfig.java
gate-core/src/main/java/com/netflix/spinnaker/gate/config/MultiAuthSupport.java
gate-web/src/test/java/com/netflix/spinnaker/gate/AuthConfigTest.java
gate-web/src/test/java/com/netflix/spinnaker/gate/MultiAuthSupportTest.java

to prevent
```
java.lang.UnsupportedOperationException: public abstract int javax.servlet.ServletRequest.getLocalPort() is not supported 
```
and HTML response bodies like:
```
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1>
```
instead of json when processing errors.
See https://github.com/spring-projects/spring-security/issues/11055#issuecomment-1098061598 for background.
https://github.com/spinnaker/gate/pull/1819 is a similar …

fix(core): remove ErrorPageSecurityFilter bean named errorPageSecurityInterceptor

---

gate-core/src/main/java/com/netflix/spinnaker/gate/services/TaskService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/controllers/PipelineControllerConfigProperties.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/FunctionalSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/PipelineControllerSpec.groovy

This is part of: https://github.com/spinnaker/spinnaker/issues/6147.
Adds a new enpdoint, POST /pipelines/bulksave, which can take a list of pipeline configurations to save. The endpoint will return a response that indicates how many of the saves were successful, how many failed, and what the failures are. The structure is
```
[
"successful_pipelines_count"  : <int>,
"successful_pipelines"        : <List<String>>,
"failed_pipelines_count"      : <int>,
"failed_pipelines"            : <List<Map<String, Object>>> 
]
```
There are a few config knobs which control some bulk save functionality. The gate endpoint invokes an orca asynchronous process to manage saving the pipelines and polls until the orca operations are complete.
```yaml
controller:
pipeline:
bulksave: …
```

Pipeline config batch update

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy

Add logging and  metrics around sending events sent to Echo when a pipeline is triggered manually.  Specifically:
* echo.events.count
* echo.events.duration
* echo.events.error
As well, this changes the `POST /pipelines/v2/{application}/{pipelineNameOrId}` endpoint (the one deck uses to trigger manual execution) to generate an event id before calling echo.  Eventually, we may move the event id generation to the UI to reduce the chance of duplicate triggers in some scenarios.

feat(instrumentation): add instrumentation around echo event handling

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/ApplicationConfigurationProperties.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ApplicationServiceSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/ApplicationControllerSpec.groovy

This PR is to address the issue of UI showing synthetic applications created by Spinnaker itself which are unknown to Front50. 
Clouddriver creates these synthetic applications when it is caching resources in a cluster. If the account doesn’t have `onlySpinnakerManaged` set to true, it will create an application using the first part of the manifest name. i.e. a deployment with a name of test-abc will result in an application called test being created.
Through https://github.com/spinnaker/clouddriver/pull/5777, Clouddriver is equipped with discarding caching manifests whose application name(derived from moniker) doesn't exist in front50 but in spite of this, synthetic applications can exist in the following scenarios:
1. When `kubernetes.checkApplicationInFront50` is not enabled in …

feat(web): add a config property that allows front50 to be the source of truth for applications

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/GateWebConfig.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ApplicationServiceSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/ApplicationControllerSpec.groovy
gate-web/src/test/java/com/netflix/spinnaker/gate/config/GateWebConfigAuthenticatedRequestFilterTest.java

so log messages contain more context, and so downstream HTTP calls include X-SPINNAKER-* headers via e.g. SpinnakerRequestInterceptor.

feat(gate): copy the MDC to async controller method handler threads

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy
gate-web/src/main/java/com/netflix/spinnaker/gate/services/MdcWrappedCallable.java
gate-web/src/test/java/com/netflix/spinnaker/gate/services/MdcWrappedCallableTest.java

populate the MDC when the ApplicationService gathers information from front50 and clouddriver  so that, for example, when gate receives an http request with an X-SPINNAKER-REQUEST-ID header, that same value appears in outgoing request headers to front50 and clouddriver.  This makes troubleshooting a whole lot easier.

feat(web): populate the MDC when the ApplicationService gathers information from front50 and clouddriver

---

gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/Front50Service.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/ApplicationServiceSpec.groovy
gate-web/src/test/java/com/netflix/spinnaker/gate/controllers/InvokePipelineConfigTest.java

- Adjust error message in PipelineController.invokePipelineConfig and use pipeline name instead of id in InvokePipelineConfigTest to reduce diffs when ApplicationService.getPipelineConfigForApplication changes the queries it makes to front50
- Change ApplicationService.getPipelineConfigForApplication to query front50 for individual pipelines instead of querying for all pipelines in an application and then filtering locally.
- Teach ApplicationService.getPipelineConfigForApplication to handle errors with SpinnakerRetrofitErrorHandler to centralize exception handling there / remove the need for callers to check for null

perf(web): Query for individual pipelines

---

gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/Front50Service.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ApplicationController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/ApplicationControllerSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/PipelineControllerSpec.groovy

This plumbs through the new pipelineNameFilter query param to the front50 service call in gate. 
Front50 changes were added as part of https://github.com/spinnaker/front50/pull/1504

feat(pipelines): add pipelineNameFilter to /{application}/pipelineConfigs endpoint

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/PagerDutyConfig.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/FunctionalSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/WebhookControllerSpec.groovy

Moving away from `com.squareup.okhttp.OkHttpClient` to `okhttp3.OkHttpClient` to avoid any unwanted dependency conflicts.
okhttp3.OkHttpClient for retrofit1 is provided by [Ok3Client](https://github.com/JakeWharton/retrofit1-okhttp3-client)

refactor(retrofit): replace OkClient with Ok3Client

---

gate-core/gate-core.gradle
gate-proxy/gate-proxy.gradle
gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/ApiExtensionController.kt
gate-web/gate-web.gradle
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/ApplicationControllerSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/AwsCodeBuildControllerSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/BuildControllerSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/EcsClusterControllerSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/GoogleCloudBuildControllerSpec.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/WebhookControllerSpec.groovy

All references to com.squareup.okhttp will be removed with this PR.
ApiExtensionController needed minor refactoring to fix the following error caused due to kotlin-java conflicts:
```
class java.lang.Object cannot be cast to class java.lang.String (java.lang.Object and java.lang.String are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.Object cannot be cast to class java.lang.String (java.lang.Object and java.lang.String are in module java.base of loader 'bootstrap')
at com.netflix.spinnaker.gate.controllers.ApiExtensionController.any(ApiExtensionController.kt:80)
at com.netflix.spinnaker.gate.controllers.ApiExtensionControllerTest$tests$1$3$2.invoke(ApiExtensionControllerTest.kt:61)
at com.netflix.spinnaker.gate.controllers.ApiExtensionControllerT …
```

refactor(retrofit): remove all com.squareup.okhttp dependencies

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/config/CloudEventHandlerConfiguration.java
gate-web/src/test/java/com/netflix/spinnaker/gate/config/GateSwaggerConfigTest.java
gate-web/src/test/resources/gate-test.yml

Starting in 1.36.x Swagger UI in Gate fails on loading the swagger ui with the follow:
the main issue is that the JSON from swagger-ui is encoded in base64.
After some investigation I found this error was reported in the following Github issue: https://github.com/springdoc/springdoc-openapi/issues/2143
In a few words, the ByteArrayHttpMessageConverter is responsible on deserialize the swagger JSON but it needs to be at the beginning of the converters. My fix just creates a ByteArrayHttpMessageConverter bean at set it as the first messageConverters.

fix(swagger): ensure byteArrayHttpMessageConverter is the first converter to render swagger UI

---

gate-core/gate-core.gradle
gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/ClouddriverService.java
gate-core/src/test/java/com/netflix/spinnaker/gate/services/internal/ClouddriverServiceTest.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ImageService.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ServiceBrokerService.java

Addressed the following two issues which occurred due to restrictions in retrofit2 :
- Map must include generic types (e.g., Map<String, String>) 
- A @Path parameter must not come after a @Query

fix(retrofit2): fix retrofit2 issues

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ImageController.groovy
gate-web/src/test/java/com/netflix/spinnaker/gate/controllers/ImageControllerTest.java

match what ImageSerice.search expects.  Since the test in the previous commit passes without this, apparently it's not required, but it removes an IDE warning, and generally feels like an improvement.
See https://github.com/spinnaker/gate/pull/1875#discussion_r1974340789 for background.

fix(web): make type of additionalFilters in ImageController.findImages

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/BakeService.groovy
gate-web/src/test/java/com/netflix/spinnaker/gate/service/BakeServiceTest.java

since (as of https://github.com/spinnaker/gate/pull/1866) RoscoService uses retrofit2.

fix(web): add Retrofit2SyncCall.execute to BakeService

---

gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/CredentialsController.groovy
gate-web/src/test/groovy/com/netflix/spinnaker/gate/controllers/CredentialsControllerSpec.groovy
gate-web/src/test/java/com/netflix/spinnaker/gate/controllers/CredentialsControllerTest.java

CredentialsController has ClouddriverService calls which needed Retrofit2SyncCall.execute.
Added a test to demonstrate the issue.

fix(web): add Retrofit2SyncCall.execute to ClouddriverService in CredentialsController

---

gate-core/src/main/java/com/netflix/spinnaker/gate/services/TaskService.java
gate-core/src/main/java/com/netflix/spinnaker/gate/services/internal/OrcaService.java
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ApplicationController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/PipelineController.groovy
gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/PipelineService.groovy
gate-web/src/test/java/com/netflix/spinnaker/gate/service/PipelineServiceTest.java

- While some of the Orca's API have void return types, Gate has `Map` return type for the corresponding APIs causing the following error : 
```
Failed to process response body: No content to map due to end-of-input\n at [Source: (okhttps.ResponseBody$BomAwareReader); line:1, column:0)
```
- Retrofit1 ignored the mismatches but retrofit2 has stricter response handling.
- This PR adds a test to demonstrate the issue and addressed the mismatches.

fix(web): fix the mismatches in the return types of APIs in gate and orca
